"""
reporter.py — Report writer. Produces Markdown, HTML, and CSV output.

Markdown: human-readable, Git-friendly, good for the repo sample.
HTML:     visual dashboard, self-contained single file.
CSV:      machine-readable compliance summary, one row per domain.
"""

import csv
import html
from datetime import datetime, timezone
from typing import Dict, List

from cloudflare_reporting.lib.remediation import get_tooltip, collect_remediations


# ── Grade helpers ─────────────────────────────────────────────────────────────

_GRADE_ORDER = {"FAIL": 0, "WARN": 1, "INFO": 2, "PASS": 3}

GRADE_SYMBOL = {
    "PASS": "✅ PASS",
    "WARN": "⚠️ WARN",
    "FAIL": "❌ FAIL",
    "INFO": "ℹ️ INFO",
}

# HTML badge classes
GRADE_CLASS = {
    "PASS": "badge-success",
    "WARN": "badge-warning",
    "FAIL": "badge-danger",
    "INFO": "badge-info",
}


# Em dash for use in f-string expressions (backslash escapes not allowed in Python 3.10 f-exprs)
_DASH = "\u2014"


def _worst(grades: List[str]) -> str:
    if not grades:
        return "INFO"
    return min(grades, key=lambda g: _GRADE_ORDER.get(g, 99))


def _sym(grade: str) -> str:
    return GRADE_SYMBOL.get(grade, grade)


def _truncate(s: str, n: int = 80) -> str:
    return s if len(s) <= n else s[:n - 3] + "..."


def _ts() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


# ══════════════════════════════════════════════════════════════════════════════
# MARKDOWN
# ══════════════════════════════════════════════════════════════════════════════

def write_markdown(
    domains: List[str],
    dns_results: Dict[str, dict],
    email_results: Dict[str, dict],
    security_results: Dict[str, dict],
    registrar_results: Dict[str, dict],
    dns_sec_results: Dict[str, dict],
    blacklist_results: Dict[str, dict],
    rdns_results: Dict[str, dict],
    email_std_results: Dict[str, dict] = None,
    output_path: str = "",
) -> None:
    sections = [
        _md_header(domains),
        _md_executive_summary(
            domains, email_results, security_results, dns_results,
            registrar_results, dns_sec_results, blacklist_results, rdns_results,
        ),
    ]

    for domain in domains:
        if domain in registrar_results:
            sections.append(_md_registrar(domain, registrar_results[domain]))
        if domain in dns_sec_results:
            sections.append(_md_dns_security(domain, dns_sec_results[domain]))
        if domain in dns_results:
            sections.append(_md_dns(domain, dns_results[domain]))
        if domain in email_results:
            sections.append(_md_email(domain, email_results[domain]))
        if domain in blacklist_results:
            sections.append(_md_blacklist(domain, blacklist_results[domain]))
        if domain in rdns_results:
            sections.append(_md_rdns(domain, rdns_results[domain]))
        if email_std_results and domain in email_std_results:
            sections.append(_md_email_standards(domain, email_std_results[domain]))
        if domain in security_results:
            sections.append(_md_security(domain, security_results[domain]))

    sections.append(
        "\n---\n\n"
        "*Generated by [cloudflare-reporting](https://github.com/wblv-dev/cloudflare-reporting). "
        "Read-only — no changes made to any zone.*\n"
    )

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(sections))

    print(f"  Markdown report → {output_path}")


def _md_header(domains: List[str]) -> str:
    domain_list = ", ".join(f"`{d}`" for d in domains)
    return (
        f"# Cloudflare DNS Audit Report\n\n"
        f"**Generated:** {_ts()}  \n"
        f"**Domains:** {domain_list}  \n"
        f"**Tool:** [cloudflare-reporting](https://github.com/wblv-dev/cloudflare-reporting)\n\n"
        f"> Live DNS validation and Cloudflare API audit. "
        f"Grades reflect published state at time of generation.\n\n---\n"
    )


def _md_executive_summary(
    domains, email_results, security_results, dns_results,
    registrar_results, dns_sec_results, blacklist_results, rdns_results,
) -> str:
    lines = [
        "## Executive summary\n",
        "| Domain | DNS | Email | Zone | Registrar | DNSSEC | CAA | Blacklist | rDNS |",
        "|--------|-----|-------|------|-----------|--------|-----|-----------|------|",
    ]

    for d in domains:
        dns_count = dns_results.get(d, {}).get("total", "?")

        email = email_results.get(d, {})
        email_grade = _worst([
            email.get("spf", {}).get("grade", "INFO"),
            email.get("dmarc", {}).get("grade", "INFO"),
        ])

        sec = security_results.get(d)
        if sec:
            passed, total = sec["score"]
            sec_cell = f"{_sym(_worst([r['grade'] for r in sec['results']]))} ({passed}/{total})"
        else:
            sec_cell = "—"

        reg = registrar_results.get(d, {})
        reg_grade = _worst([
            reg.get("expiry", {}).get("grade", "INFO"),
            reg.get("lock", {}).get("grade", "INFO"),
        ])

        ds = dns_sec_results.get(d, {})
        dnssec_g = ds.get("dnssec", {}).get("grade", "?")
        caa_g = ds.get("caa", {}).get("grade", "?")

        bl_g = blacklist_results.get(d, {}).get("grade", "?")
        rdns_g = rdns_results.get(d, {}).get("grade", "?")

        lines.append(
            f"| `{d}` | {dns_count} | {_sym(email_grade)} | {sec_cell} "
            f"| {_sym(reg_grade)} | {_sym(dnssec_g)} | {_sym(caa_g)} "
            f"| {_sym(bl_g)} | {_sym(rdns_g)} |"
        )

    return "\n".join(lines) + "\n\n---\n"


def _md_registrar(domain: str, result: dict) -> str:
    lines = [f"## Registrar — `{domain}`\n"]

    if result.get("registrar"):
        lines.append(f"**Registrar:** {result['registrar']}\n")

    if result.get("nameservers"):
        lines.append(f"**Nameservers:** {', '.join(f'`{ns}`' for ns in result['nameservers'])}\n")

    exp = result.get("expiry", {})
    lines.append(f"**Expiry:** {_sym(exp.get('grade', 'INFO'))} — {exp.get('reason', 'Unknown')}")
    if exp.get("expiry"):
        lines.append(f"  \n**Expiry date:** `{exp['expiry']}`")

    lock = result.get("lock", {})
    lines.append(f"\n**Transfer lock:** {_sym(lock.get('grade', 'INFO'))} — {lock.get('reason', 'Unknown')}")

    return "\n".join(lines) + "\n\n"


def _md_dns_security(domain: str, result: dict) -> str:
    lines = [f"## DNS security — `{domain}`\n"]

    dnssec = result.get("dnssec", {})
    lines.append(f"**DNSSEC:** {_sym(dnssec.get('grade', 'INFO'))} — {dnssec.get('reason', '')}")

    caa = result.get("caa", {})
    lines.append(f"\n**CAA:** {_sym(caa.get('grade', 'INFO'))} — {caa.get('reason', '')}")

    if caa.get("records"):
        lines += ["\n| Flags | Tag | Value |", "|-------|-----|-------|"]
        for r in caa["records"]:
            lines.append(f"| {r.get('flags', '')} | `{r.get('tag', '')}` | `{r.get('value', '')}` |")

    dangling = result.get("dangling", {})
    lines.append(f"\n**Dangling CNAMEs:** {_sym(dangling.get('grade', 'INFO'))} — {dangling.get('reason', '')}")

    if dangling.get("dangling"):
        lines += ["\n| Record | Target |", "|--------|--------|"]
        for d in dangling["dangling"]:
            lines.append(f"| `{d['name']}` | `{d['target']}` |")

    return "\n".join(lines) + "\n\n"


def _md_blacklist(domain: str, result: dict) -> str:
    lines = [
        f"## Blacklist — `{domain}`\n",
        f"**Status:** {_sym(result.get('grade', 'INFO'))} — {result.get('reason', '')}",
    ]

    listings = result.get("listings", [])
    if listings:
        lines += ["\n| IP | Blacklist | Reason |", "|-----|-----------|--------|"]
        for l in listings:
            lines.append(f"| `{l.get('ip', '')}` | {l.get('blacklist', '')} | {l.get('reason', '')} |")

    return "\n".join(lines) + "\n\n"


def _md_rdns(domain: str, result: dict) -> str:
    lines = [
        f"## Reverse DNS — `{domain}`\n",
        f"**Status:** {_sym(result.get('grade', 'INFO'))} — {result.get('reason', '')}",
    ]

    ptr_results = result.get("results", [])
    if ptr_results:
        lines += ["\n| MX Host | IP | PTR | FCrDNS |", "|---------|-----|-----|--------|"]
        for r in ptr_results:
            fcrdns = "✅" if r.get("fcrdns") else "❌"
            ptr = r.get("ptr") or "—"
            lines.append(
                f"| `{r.get('mx_host', '')}` | `{r.get('ip', '')}` | `{ptr}` | {fcrdns} |"
            )

    return "\n".join(lines) + "\n\n"


def _md_email_standards(domain: str, result: dict) -> str:
    lines = [f"## Email standards — `{domain}`\n"]

    mta = result.get("mta_sts", {})
    lines.append(f"**MTA-STS:** {_sym(mta.get('grade', 'INFO'))} — {mta.get('reason', '')}")
    if mta.get("mode"):
        lines.append(f"  \n**Mode:** `{mta['mode']}`")

    tls = result.get("tlsrpt", {})
    lines.append(f"\n**TLSRPT:** {_sym(tls.get('grade', 'INFO'))} — {tls.get('reason', '')}")
    if tls.get("rua"):
        lines.append(f"  \n**Reporting:** `{tls['rua']}`")

    bimi = result.get("bimi", {})
    lines.append(f"\n**BIMI:** {_sym(bimi.get('grade', 'INFO'))} — {bimi.get('reason', '')}")

    return "\n".join(lines) + "\n\n"


def _md_dns(domain: str, summary: dict) -> str:
    lines = [f"## DNS inventory — `{domain}`\n",
             f"**Total:** {summary['total']} records  "
             f"(**{summary['proxied']}** proxied through Cloudflare)\n",
             "**By type:**\n",
             "| Type | Count |", "|------|-------|"]
    for rtype, count in summary["by_type"].items():
        lines.append(f"| `{rtype}` | {count} |")

    lines += ["\n**All records:**\n",
              "| Type | Name | Content | TTL | Proxied |",
              "|------|------|---------|-----|---------|"]
    for r in sorted(summary["records"], key=lambda x: (x["type"], x["name"])):
        proxied = "🟠 Yes" if r["proxied"] else "No"
        lines.append(
            f"| `{r['type']}` | `{r['name']}` "
            f"| `{_truncate(r['content'], 60)}` | {r['ttl']} | {proxied} |"
        )
    return "\n".join(lines) + "\n\n"


def _md_email(domain: str, result: dict) -> str:
    lines = [f"## Email security — `{domain}`\n"]

    if not result["has_mail"]:
        lines.append("**MX:** " + (
            "None — domain does not handle email.\n"
            if not result["mx"]
            else "Null MX (RFC 7505) — domain explicitly declares no mail.\n"
        ))
    else:
        lines += ["**MX records:**\n", "| Priority | Host |", "|----------|------|"]
        for mx in result["mx"]:
            lines.append(f"| {mx['priority']} | `{mx['host']}` |")
        lines.append("")

    spf   = result["spf"]
    dmarc = result["dmarc"]

    lines.append(f"**SPF:** {_sym(spf['grade'])} — {spf['reason']}")
    if spf.get("record"):
        lines.append(f"\n```\n{spf['record']}\n```\n")

    lines.append(f"**DMARC:** {_sym(dmarc['grade'])} — {dmarc['reason']}")
    if dmarc.get("rua"):
        lines.append(f"  \n**Reporting (rua):** `{dmarc['rua']}`")
    if dmarc.get("record"):
        lines.append(f"\n```\n{dmarc['record']}\n```\n")

    if result["dkim"]:
        lines += ["**DKIM selectors found:**\n",
                  "| Selector | Record (truncated) |",
                  "|----------|--------------------|"]
        for dk in result["dkim"]:
            lines.append(f"| `{dk['selector']}` | `{_truncate(dk['record'], 60)}` |")
    else:
        lines.append(
            "**DKIM:** No common selectors found. "
            "Add your provider's selector to `DKIM_SELECTORS` in `cloudflare_reporting/checks/email_security.py`.\n"
        )

    return "\n".join(lines) + "\n"


def _md_security(domain: str, result: dict) -> str:
    passed, total = result["score"]
    lines = [f"## Zone security — `{domain}`\n",
             f"**Score:** {passed}/{total} checks passed\n",
             "| Check | Recommended | Actual | Grade | Notes |",
             "|-------|-------------|--------|-------|-------|"]
    for r in result["results"]:
        lines.append(
            f"| {r['label']} | `{r.get('recommended','—')}` "
            f"| `{r.get('actual','—')}` | {_sym(r['grade'])} | {r.get('note','')} |"
        )

    failures = [r for r in result["results"] if r["grade"] in ("FAIL", "WARN")]
    if failures:
        lines.append("\n**Findings:**\n")
        for r in failures:
            if r.get("explanation"):
                lines.append(f"- **{r['label']}** ({_sym(r['grade'])}): {r['explanation']}")

    return "\n".join(lines) + "\n\n"


# ══════════════════════════════════════════════════════════════════════════════
# CSV
# ══════════════════════════════════════════════════════════════════════════════

def write_csv(
    domains: List[str],
    dns_results: Dict[str, dict],
    email_results: Dict[str, dict],
    security_results: Dict[str, dict],
    registrar_results: Dict[str, dict],
    dns_sec_results: Dict[str, dict],
    blacklist_results: Dict[str, dict],
    rdns_results: Dict[str, dict],
    email_std_results: Dict[str, dict] = None,
    output_path: str = "",
) -> None:
    """Write a CSV compliance summary — one row per domain."""
    fieldnames = [
        "Domain", "DNS Records",
        "SPF", "DMARC", "DKIM Selectors",
        "Zone Security", "Zone Pass", "Zone Total",
        "Registrar", "Expiry", "Expiry Days", "Transfer Lock",
        "DNSSEC", "CAA", "Dangling CNAMEs",
        "Blacklist", "Reverse DNS",
        "MTA-STS", "TLSRPT", "BIMI",
    ]

    _estd = email_std_results or {}
    rows = []
    for d in domains:
        dns = dns_results.get(d, {})
        email = email_results.get(d, {})
        sec = security_results.get(d, {})
        reg = registrar_results.get(d, {})
        ds = dns_sec_results.get(d, {})
        bl = blacklist_results.get(d, {})
        rdns = rdns_results.get(d, {})
        es = _estd.get(d, {})

        passed, total = sec.get("score", (0, 0))

        rows.append({
            "Domain":          d,
            "DNS Records":     dns.get("total", 0),
            "SPF":             email.get("spf", {}).get("grade", ""),
            "DMARC":           email.get("dmarc", {}).get("grade", ""),
            "DKIM Selectors":  len(email.get("dkim", [])),
            "Zone Security":   _worst([r["grade"] for r in sec.get("results", [])]) if sec.get("results") else "",
            "Zone Pass":       passed,
            "Zone Total":      total,
            "Registrar":       reg.get("registrar", ""),
            "Expiry":          reg.get("expiry", {}).get("grade", ""),
            "Expiry Days":     reg.get("expiry", {}).get("days_remaining", ""),
            "Transfer Lock":   reg.get("lock", {}).get("grade", ""),
            "DNSSEC":          ds.get("dnssec", {}).get("grade", ""),
            "CAA":             ds.get("caa", {}).get("grade", ""),
            "Dangling CNAMEs": len(ds.get("dangling", {}).get("dangling", [])),
            "Blacklist":       bl.get("grade", ""),
            "Reverse DNS":     rdns.get("grade", ""),
            "MTA-STS":         es.get("mta_sts", {}).get("grade", ""),
            "TLSRPT":          es.get("tlsrpt", {}).get("grade", ""),
            "BIMI":            es.get("bimi", {}).get("grade", ""),
        })

    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"  CSV report      → {output_path}")



# ══════════════════════════════════════════════════════════════════════════════
# HTML
# ══════════════════════════════════════════════════════════════════════════════

import json as _json
import os as _os


def _read_chartjs() -> str:
    """Read the Chart.js UMD bundle from /tmp/chartjs.min.js."""
    chartjs_path = _os.path.join("/tmp", "chartjs.min.js")
    try:
        with open(chartjs_path, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        return "/* Chart.js not found at /tmp/chartjs.min.js */"


def _load_template() -> str:
    """Load the HTML template from cloudflare_reporting/template.html."""
    template_dir = _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__)))
    template_path = _os.path.join(template_dir, "template.html")
    with open(template_path, "r", encoding="utf-8") as f:
        return f.read()


def write_html(
    domains: List[str],
    dns_results: Dict[str, dict],
    email_results: Dict[str, dict],
    security_results: Dict[str, dict],
    registrar_results: Dict[str, dict],
    dns_sec_results: Dict[str, dict],
    blacklist_results: Dict[str, dict],
    rdns_results: Dict[str, dict],
    email_std_results: Dict[str, dict] = None,
    output_path: str = "",
) -> None:
    _estd = email_std_results or {}

    # Load template
    tpl = _load_template()

    # Read Chart.js
    chartjs_src = _read_chartjs()

    # Collect remediations
    remediations = collect_remediations(
        domains, security_results, email_results,
        dns_sec_results, registrar_results, blacklist_results, rdns_results,
    )

    # Aggregate grades across all domains
    all_grades = _collect_all_grades(
        domains, security_results, email_results,
        dns_sec_results, registrar_results, blacklist_results, rdns_results,
    )
    total_pass = all_grades["PASS"]
    total_warn = all_grades["WARN"]
    total_fail = all_grades["FAIL"]
    total_info = all_grades["INFO"]
    total_checks = total_pass + total_warn + total_fail + total_info
    compliance_pct = round(total_pass / total_checks * 100) if total_checks else 0

    # Total DNS records
    total_records = sum(
        dns_results.get(d, {}).get("total", 0) for d in domains
    )

    # Category breakdown for stacked bars
    cat_data = _category_breakdown(
        domains, security_results, email_results,
        dns_sec_results, registrar_results, blacklist_results, rdns_results,
    )

    # Per-domain grade data for mini donuts
    domain_grades = {}
    for d in domains:
        dg = _collect_domain_grades(
            d, security_results, email_results,
            dns_sec_results, registrar_results, blacklist_results, rdns_results,
        )
        domain_grades[d] = dg

    # Build dynamic HTML fragments
    category_bars_html = _build_category_bars(cat_data)
    heatmap_html = _build_heatmap(
        domains, security_results, email_results,
        dns_sec_results, registrar_results, blacklist_results, rdns_results,
    )
    domain_cards_html = _build_domain_cards(
        domains, domain_grades, email_results, security_results,
        dns_results, registrar_results, dns_sec_results,
        blacklist_results, rdns_results,
    )
    findings_html = _build_findings(remediations)
    detail_sections_html = _build_detail_sections(
        domains, security_results, email_results, _estd,
        dns_sec_results, registrar_results, blacklist_results,
        rdns_results, dns_results,
    )

    # Build audit JSON for Chart.js
    domain_chart_list = []
    for d in domains:
        dg = domain_grades.get(d, {})
        domain_chart_list.append({
            "pass": dg.get("PASS", 0),
            "warn": dg.get("WARN", 0),
            "fail": dg.get("FAIL", 0),
        })
    audit_json = _json.dumps({
        "pass": total_pass,
        "warn": total_warn,
        "fail": total_fail,
        "info": total_info,
        "domainCharts": domain_chart_list,
    })

    # Replace placeholders in template
    out = tpl
    out = out.replace("/*CHARTJS_PLACEHOLDER*/", chartjs_src)
    out = out.replace("{{GENERATED}}", _esc(_ts()))
    out = out.replace("{{DOMAIN_COUNT}}", str(len(domains)))
    out = out.replace("{{TOTAL_RECORDS}}", str(total_records))
    out = out.replace("{{COMPLIANCE_PCT}}", str(compliance_pct))
    out = out.replace("{{PASS_COUNT}}", str(total_pass))
    out = out.replace("{{WARN_COUNT}}", str(total_warn))
    out = out.replace("{{FAIL_COUNT}}", str(total_fail))
    out = out.replace("{{CATEGORY_BARS}}", category_bars_html)
    out = out.replace("{{HEATMAP}}", heatmap_html)
    out = out.replace("{{DOMAIN_CARDS}}", domain_cards_html)
    out = out.replace("{{FINDING_COUNT}}", str(len(remediations)))
    out = out.replace("{{FINDINGS}}", findings_html)
    out = out.replace("{{DETAIL_SECTIONS}}", detail_sections_html)
    out = out.replace("{{AUDIT_JSON}}", audit_json)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(out)

    print(f"  HTML report     \u2192 {output_path}")


# ── Helpers (must remain exactly as-is) ──────────────────────────────────────

def _esc(s) -> str:
    """HTML-escape untrusted content to prevent XSS."""
    if s is None:
        return ""
    return html.escape(str(s))


def _badge(grade: str, text: str = None) -> str:
    cls  = GRADE_CLASS.get(grade, "badge-info")
    label = text or grade
    return f'<span class="badge {cls}">{_esc(label)}</span>'


def _tip(label: str) -> str:
    """Wrap a label in a tooltip span if a tooltip exists for it."""
    tooltip_text = get_tooltip(label)
    if tooltip_text:
        return (
            f'<span class="has-tooltip" data-tooltip="{_esc(tooltip_text)}">'
            f'{_esc(label)}</span>'
        )
    return _esc(label)


# ── Grade aggregation helpers ────────────────────────────────────────────────

def _collect_all_grades(
    domains, security_results, email_results,
    dns_sec_results, registrar_results, blacklist_results, rdns_results,
) -> dict:
    """Count PASS/WARN/FAIL/INFO across every check on every domain."""
    counts = {"PASS": 0, "WARN": 0, "FAIL": 0, "INFO": 0}
    for d in domains:
        dg = _collect_domain_grades(
            d, security_results, email_results,
            dns_sec_results, registrar_results, blacklist_results, rdns_results,
        )
        for k in counts:
            counts[k] += dg.get(k, 0)
    return counts


def _collect_domain_grades(
    domain, security_results, email_results,
    dns_sec_results, registrar_results, blacklist_results, rdns_results,
) -> dict:
    """Count PASS/WARN/FAIL/INFO for a single domain."""
    counts = {"PASS": 0, "WARN": 0, "FAIL": 0, "INFO": 0}

    def _inc(grade: str) -> None:
        counts[grade] = counts.get(grade, 0) + 1

    sec = security_results.get(domain)
    if sec:
        for r in sec.get("results", []):
            _inc(r.get("grade", "INFO"))

    email = email_results.get(domain, {})
    for key in ("spf", "dmarc"):
        _inc(email.get(key, {}).get("grade", "INFO"))

    ds = dns_sec_results.get(domain, {})
    for key in ("dnssec", "caa", "dangling"):
        _inc(ds.get(key, {}).get("grade", "INFO"))

    reg = registrar_results.get(domain, {})
    for key in ("expiry", "lock"):
        _inc(reg.get(key, {}).get("grade", "INFO"))

    _inc(blacklist_results.get(domain, {}).get("grade", "INFO"))
    _inc(rdns_results.get(domain, {}).get("grade", "INFO"))

    return counts


def _category_breakdown(
    domains, security_results, email_results,
    dns_sec_results, registrar_results, blacklist_results, rdns_results,
) -> dict:
    """Return {category: {PASS, WARN, FAIL}} for the stacked bar chart."""
    cats = {
        "Zone Security": {"PASS": 0, "WARN": 0, "FAIL": 0},
        "Email": {"PASS": 0, "WARN": 0, "FAIL": 0},
        "DNS Security": {"PASS": 0, "WARN": 0, "FAIL": 0},
        "Infrastructure": {"PASS": 0, "WARN": 0, "FAIL": 0},
    }
    for d in domains:
        sec = security_results.get(d)
        if sec:
            for r in sec.get("results", []):
                g = r.get("grade", "INFO")
                if g in cats["Zone Security"]:
                    cats["Zone Security"][g] += 1

        email = email_results.get(d, {})
        for key in ("spf", "dmarc"):
            g = email.get(key, {}).get("grade", "INFO")
            if g in cats["Email"]:
                cats["Email"][g] += 1

        ds = dns_sec_results.get(d, {})
        for key in ("dnssec", "caa", "dangling"):
            g = ds.get(key, {}).get("grade", "INFO")
            if g in cats["DNS Security"]:
                cats["DNS Security"][g] += 1

        reg = registrar_results.get(d, {})
        for key in ("expiry", "lock"):
            g = reg.get(key, {}).get("grade", "INFO")
            if g in cats["Infrastructure"]:
                cats["Infrastructure"][g] += 1

        bl_g = blacklist_results.get(d, {}).get("grade", "INFO")
        if bl_g in cats["Infrastructure"]:
            cats["Infrastructure"][bl_g] += 1
        rdns_g = rdns_results.get(d, {}).get("grade", "INFO")
        if rdns_g in cats["Infrastructure"]:
            cats["Infrastructure"][rdns_g] += 1

    return cats


# ── Priority helpers ─────────────────────────────────────────────────────────

_PRIORITY_CLASS = {
    "Critical": "badge-danger",
    "High": "badge-warning",
    "Medium": "badge-info",
    "Low": "badge-info",
}

_PRIORITY_COLOR = {
    "Critical": "#dc2626",
    "High": "#d97706",
    "Medium": "#3b82f6",
    "Low": "#94a3b8",
}

_PRIORITY_BORDER = {
    "Critical": "#dc2626",
    "High": "#d97706",
    "Medium": "#eab308",
    "Low": "#3b82f6",
}


# ── Heatmap color helpers ────────────────────────────────────────────────────

_HEAT_CLASS = {
    "PASS": "heat-green",
    "WARN": "heat-amber",
    "FAIL": "heat-red",
    "INFO": "heat-green",
}


# ══════════════════════════════════════════════════════════════════════════════
# HTML fragment builders  (each returns a string to inject into {{PLACEHOLDER}})
# ══════════════════════════════════════════════════════════════════════════════

def _build_category_bars(cat_data: dict) -> str:
    """Build horizontal stacked progress bars for each category."""
    parts = []
    for cat_name, counts in cat_data.items():
        total = counts["PASS"] + counts["WARN"] + counts["FAIL"]
        if total == 0:
            pct_pass = pct_warn = pct_fail = 0
        else:
            pct_pass = round(counts["PASS"] / total * 100, 1)
            pct_warn = round(counts["WARN"] / total * 100, 1)
            pct_fail = round(counts["FAIL"] / total * 100, 1)
        score = f'{counts["PASS"]}/{total}'
        parts.append(
            f'<div class="progress-row">'
            f'<div class="label">{_esc(cat_name)}</div>'
            f'<div class="progress-track">'
            f'<div class="progress-segment" style="width:{pct_pass}%;background:#059669"></div>'
            f'<div class="progress-segment" style="width:{pct_warn}%;background:#d97706"></div>'
            f'<div class="progress-segment" style="width:{pct_fail}%;background:#dc2626"></div>'
            f'</div>'
            f'<div class="score">{score}</div>'
            f'</div>'
        )
    return "\n".join(parts)


def _build_heatmap(
    domains, security_results, email_results,
    dns_sec_results, registrar_results, blacklist_results, rdns_results,
) -> str:
    """Build a risk heatmap grid: domains as rows, categories as columns."""
    categories = ["Zone Security", "Email", "DNS Security", "Infrastructure"]

    # Header row
    cells = ['<div class="heatmap">']
    cells.append('<div class="header-cell"></div>')  # empty top-left
    for cat in categories:
        cells.append(f'<div class="header-cell">{_esc(cat)}</div>')

    for domain in domains:
        cells.append(f'<div class="label-cell">{_esc(domain)}</div>')

        # Zone Security: worst grade from security_results
        sec = security_results.get(domain)
        if sec:
            zone_grades = [r.get("grade", "INFO") for r in sec.get("results", [])]
            zone_worst = _worst(zone_grades) if zone_grades else "INFO"
        else:
            zone_worst = "INFO"

        # Email: worst of SPF + DMARC
        email = email_results.get(domain, {})
        email_grades = [
            email.get("spf", {}).get("grade", "INFO"),
            email.get("dmarc", {}).get("grade", "INFO"),
        ]
        email_worst = _worst(email_grades)

        # DNS Security: worst of DNSSEC + CAA + Dangling
        ds = dns_sec_results.get(domain, {})
        dns_grades = [
            ds.get("dnssec", {}).get("grade", "INFO"),
            ds.get("caa", {}).get("grade", "INFO"),
            ds.get("dangling", {}).get("grade", "INFO"),
        ]
        dns_worst = _worst(dns_grades)

        # Infrastructure: worst of expiry + lock + blacklist + rdns
        reg = registrar_results.get(domain, {})
        infra_grades = [
            reg.get("expiry", {}).get("grade", "INFO"),
            reg.get("lock", {}).get("grade", "INFO"),
            blacklist_results.get(domain, {}).get("grade", "INFO"),
            rdns_results.get(domain, {}).get("grade", "INFO"),
        ]
        infra_worst = _worst(infra_grades)

        for w in [zone_worst, email_worst, dns_worst, infra_worst]:
            hcls = _HEAT_CLASS.get(w, "heat-green")
            cells.append(f'<div class="cell {hcls}">{_esc(w)}</div>')

    cells.append('</div>')
    return "\n".join(cells)


def _build_domain_cards(
    domains, domain_grades, email_results, security_results,
    dns_results, registrar_results, dns_sec_results,
    blacklist_results, rdns_results,
) -> str:
    """Build per-domain expandable cards with mini donut canvas and badge summaries."""
    parts = []

    for idx, domain in enumerate(domains):
        dg = domain_grades.get(domain, {})

        # Build grade badges
        email = email_results.get(domain, {})
        spf_g = email.get("spf", {}).get("grade", "INFO")
        dmarc_g = email.get("dmarc", {}).get("grade", "INFO")

        ds = dns_sec_results.get(domain, {})
        dnssec_g = ds.get("dnssec", {}).get("grade", "INFO")
        caa_g = ds.get("caa", {}).get("grade", "INFO")

        sec = security_results.get(domain)
        if sec:
            passed, total = sec["score"]
            sec_grade = _worst([r["grade"] for r in sec["results"]])
            zone_badge = _badge(sec_grade, f"Zone {passed}/{total}")
        else:
            zone_badge = _badge("INFO", "Zone N/A")

        bl_g = blacklist_results.get(domain, {}).get("grade", "INFO")
        rdns_g = rdns_results.get(domain, {}).get("grade", "INFO")

        # Build detail table rows
        detail_rows = ""
        if sec:
            for r in sec["results"]:
                detail_rows += (
                    f'<tr><td>Zone Security</td><td>{_tip(r["label"])}</td>'
                    f'<td><code>{_esc(r.get("recommended", _DASH))}</code></td>'
                    f'<td><code>{_esc(r.get("actual", _DASH))}</code></td>'
                    f'<td>{_badge(r["grade"])}</td></tr>\n'
                )

        for check_key, check_label, cat in [
            ("spf", "SPF", "Email"),
            ("dmarc", "DMARC", "Email"),
        ]:
            ck = email.get(check_key, {})
            detail_rows += (
                f'<tr><td>{_esc(cat)}</td><td>{_tip(check_label)}</td>'
                f'<td>{_DASH}</td>'
                f'<td><small>{_esc(ck.get("reason", ""))}</small></td>'
                f'<td>{_badge(ck.get("grade", "INFO"))}</td></tr>\n'
            )

        for check_key, check_label in [("dnssec", "DNSSEC"), ("caa", "CAA"), ("dangling", "Dangling CNAMEs")]:
            ck = ds.get(check_key, {})
            detail_rows += (
                f'<tr><td>DNS</td><td>{_tip(check_label)}</td>'
                f'<td>{_DASH}</td>'
                f'<td><small>{_esc(ck.get("reason", ""))}</small></td>'
                f'<td>{_badge(ck.get("grade", "INFO"))}</td></tr>\n'
            )

        reg = registrar_results.get(domain, {})
        for check_key, check_label in [("expiry", "Domain expiry"), ("lock", "Transfer lock")]:
            ck = reg.get(check_key, {})
            detail_rows += (
                f'<tr><td>Infrastructure</td><td>{_tip(check_label)}</td>'
                f'<td>{_DASH}</td>'
                f'<td><small>{_esc(ck.get("reason", ""))}</small></td>'
                f'<td>{_badge(ck.get("grade", "INFO"))}</td></tr>\n'
            )

        bl = blacklist_results.get(domain, {})
        detail_rows += (
            f'<tr><td>Infrastructure</td><td>{_tip("Blacklist (DNSBL)")}</td>'
            f'<td>{_DASH}</td>'
            f'<td><small>{_esc(bl.get("reason", ""))}</small></td>'
            f'<td>{_badge(bl.get("grade", "INFO"))}</td></tr>\n'
        )

        rdns = rdns_results.get(domain, {})
        detail_rows += (
            f'<tr><td>Infrastructure</td><td>{_tip("Reverse DNS")}</td>'
            f'<td>{_DASH}</td>'
            f'<td><small>{_esc(rdns.get("reason", ""))}</small></td>'
            f'<td>{_badge(rdns.get("grade", "INFO"))}</td></tr>\n'
        )

        dns_count = dns_results.get(domain, {}).get("total", 0)

        badges_html = (
            f'{_badge(spf_g, "SPF")} {_badge(dmarc_g, "DMARC")} '
            f'{_badge(dnssec_g, "DNSSEC")} {_badge(caa_g, "CAA")} '
            f'{zone_badge} {_badge(bl_g, "Blacklist")} {_badge(rdns_g, "rDNS")}'
        )

        parts.append(
            f'<div class="domain-card" data-domain="{_esc(domain)}">'
            f'<div class="domain-header" onclick="toggleDomain(this)">'
            f'<div>'
            f'<h3>{_esc(domain)} <span style="color:#94a3b8;font-weight:400;font-size:.8em">'
            f'{_DASH} {dns_count} DNS records</span></h3>'
            f'<div class="domain-badges" style="margin-top:8px">{badges_html}</div>'
            f'</div>'
            f'<div style="display:flex;align-items:center;gap:16px">'
            f'<div class="domain-chart">'
            f'<canvas id="domainDonut{idx}" width="80" height="80"></canvas>'
            f'</div>'
            f'<span class="chevron">&#9660;</span>'
            f'</div>'
            f'</div>'
            f'<div class="domain-body">'
            f'<div class="domain-body-inner">'
            f'<table>'
            f'<thead><tr><th>Category</th><th>Check</th><th>Recommended</th>'
            f'<th>Actual</th><th>Grade</th></tr></thead>'
            f'<tbody>{detail_rows}</tbody>'
            f'</table>'
            f'</div>'
            f'</div>'
            f'</div>'
        )

    return "\n".join(parts)


def _build_findings(remediations: List[Dict]) -> str:
    """Build remediation finding cards."""
    if not remediations:
        return '<div style="text-align:center;padding:40px;color:#94a3b8">No findings requiring attention.</div>'

    parts = []

    for finding in remediations:
        prio = finding.get("priority", "Low")
        prio_css = prio.lower()
        prio_cls = _PRIORITY_CLASS.get(prio, "badge-info")
        grade_badge = _badge(finding["grade"])
        prio_badge = f'<span class="badge {prio_cls}">{_esc(prio)}</span>'

        steps = finding.get("steps", [])
        steps_html = ""
        if steps:
            step_items = "".join(f'<li>{_esc(s)}</li>' for s in steps)
            steps_html = f'<ol class="finding-steps">{step_items}</ol>'

        parts.append(
            f'<div class="finding {prio_css}" data-domain="{_esc(finding.get("domain", ""))}">'
            f'<div class="finding-header">'
            f'{prio_badge} {grade_badge} '
            f'<span class="finding-domain">{_esc(finding.get("domain", ""))}</span>'
            f'<span class="finding-check">{_tip(finding.get("check", ""))}</span>'
            f'</div>'
            f'<div class="finding-risk"><strong>Risk:</strong> {_esc(finding.get("risk", ""))}</div>'
            f'{steps_html}'
            f'</div>'
        )

    return "\n".join(parts)


def _build_detail_sections(
    domains, security_results, email_results, email_std_results,
    dns_sec_results, registrar_results, blacklist_results,
    rdns_results, dns_results,
) -> str:
    """Build all collapsible detailed check sections."""
    parts = []
    parts.append(_build_detail_zone_security(domains, security_results))
    parts.append(_build_detail_email(domains, email_results))
    parts.append(_build_detail_email_standards(domains, email_std_results))
    parts.append(_build_detail_dns_security(domains, dns_sec_results))
    parts.append(_build_detail_infrastructure(
        domains, registrar_results, blacklist_results, rdns_results,
    ))
    parts.append(_build_detail_dns_inventory(domains, dns_results))
    return "\n".join(parts)


def _collapsible(section_id: str, title: str, body: str) -> str:
    return (
        f'<button class="collapse-btn" onclick="toggleCollapse(this)">'
        f'&#9660; {title}</button>'
        f'<div class="collapse-content">{body}</div>'
    )


def _build_detail_zone_security(domains, security_results) -> str:
    if not security_results:
        return _collapsible("zone", "Zone Security Settings",
                            '<p style="color:#94a3b8;padding:16px">No zone security data available.</p>')
    rows = ""
    for domain in domains:
        sec = security_results.get(domain)
        if not sec:
            continue
        for r in sec["results"]:
            rows += (
                f'<tr data-domain="{_esc(domain)}">'
                f'<td><code>{_esc(domain)}</code></td>'
                f'<td>{_tip(r["label"])}</td>'
                f'<td><code>{_esc(r.get("recommended", _DASH))}</code></td>'
                f'<td><code>{_esc(r.get("actual", _DASH))}</code></td>'
                f'<td>{_badge(r["grade"])}</td></tr>\n'
            )

    table = (
        '<table><thead><tr><th>Domain</th><th>Check</th>'
        '<th>Recommended</th><th>Actual</th><th>Grade</th></tr></thead>'
        f'<tbody>{rows}</tbody></table>'
    )
    return _collapsible("zone", "Zone Security Settings", table)


def _build_detail_email(domains, email_results) -> str:
    if not email_results:
        return _collapsible("email", "Email Security",
                            '<p style="color:#94a3b8;padding:16px">No email security data available.</p>')

    body_parts = []
    for domain in domains:
        result = email_results.get(domain)
        if not result:
            continue

        spf = result["spf"]
        dmarc = result["dmarc"]
        dkim_count = len(result["dkim"])

        rows = (
            f'<tr><td>{_tip("SPF")}</td><td>{_badge(spf["grade"])}</td>'
            f'<td>{_esc(spf["reason"])}</td></tr>'
            f'<tr><td>{_tip("DMARC")}</td><td>{_badge(dmarc["grade"])}</td>'
            f'<td>{_esc(dmarc["reason"])}</td></tr>'
            f'<tr><td>{_tip("DKIM")}</td><td>{_badge("PASS" if dkim_count else "INFO")}</td>'
            f'<td>{dkim_count} selector(s) found</td></tr>'
        )

        spf_record = ""
        if spf.get("record"):
            spf_record = (
                f'<div style="margin:8px 0"><code style="word-break:break-all;'
                f'display:block;padding:10px;border-radius:6px">'
                f'{_esc(spf["record"])}</code></div>'
            )

        dmarc_record = ""
        if dmarc.get("record"):
            dmarc_record = (
                f'<div style="margin:8px 0"><code style="word-break:break-all;'
                f'display:block;padding:10px;border-radius:6px">'
                f'{_esc(dmarc["record"])}</code></div>'
            )

        dkim_html = ""
        if result["dkim"]:
            dkim_rows = "".join(
                f'<tr><td><code>{_esc(dk["selector"])}</code></td>'
                f'<td><code>{_esc(_truncate(dk["record"], 60))}</code></td></tr>'
                for dk in result["dkim"]
            )
            dkim_html = (
                f'<div style="margin-top:12px"><strong>{_tip("DKIM")} Selectors</strong></div>'
                f'<table><thead><tr><th>Selector</th><th>Record</th></tr></thead>'
                f'<tbody>{dkim_rows}</tbody></table>'
            )

        mx_html = ""
        if result["has_mail"] and result["mx"]:
            mx_rows = "".join(
                f'<tr><td>{m["priority"]}</td><td><code>{_esc(m["host"])}</code></td></tr>'
                for m in result["mx"]
            )
            mx_html = (
                f'<div style="margin-top:12px"><strong>MX Records</strong></div>'
                f'<table><thead><tr><th>Priority</th><th>Host</th></tr></thead>'
                f'<tbody>{mx_rows}</tbody></table>'
            )

        body_parts.append(
            f'<h4 style="color:#60a5fa;margin:20px 0 8px"><code>{_esc(domain)}</code></h4>'
            f'<table><thead><tr><th>Check</th><th>Grade</th><th>Details</th></tr></thead>'
            f'<tbody>{rows}</tbody></table>'
            f'{spf_record}{dmarc_record}{mx_html}{dkim_html}'
        )

    return _collapsible("email", "Email Security", "\n".join(body_parts))


def _build_detail_email_standards(domains, email_std_results) -> str:
    if not email_std_results:
        return _collapsible(
            "email-std",
            f"Email Standards ({_tip('MTA-STS')} / {_tip('TLSRPT')} / {_tip('BIMI')})",
            '<p style="color:#94a3b8;padding:16px">No email standards data available.</p>',
        )

    rows = ""
    for domain in domains:
        result = email_std_results.get(domain)
        if not result:
            continue
        mta = result.get("mta_sts", {})
        tls = result.get("tlsrpt", {})
        bimi = result.get("bimi", {})
        rows += (
            f'<tr data-domain="{_esc(domain)}">'
            f'<td><code>{_esc(domain)}</code></td>'
            f'<td>{_badge(mta.get("grade", "INFO"))} '
            f'<small>{_esc(mta.get("reason", ""))}</small></td>'
            f'<td>{_badge(tls.get("grade", "INFO"))} '
            f'<small>{_esc(tls.get("reason", ""))}</small></td>'
            f'<td>{_badge(bimi.get("grade", "INFO"))} '
            f'<small>{_esc(bimi.get("reason", ""))}</small></td></tr>\n'
        )

    table = (
        f'<table><thead><tr><th>Domain</th>'
        f'<th>{_tip("MTA-STS")}</th><th>{_tip("TLSRPT")}</th><th>{_tip("BIMI")}</th>'
        f'</tr></thead><tbody>{rows}</tbody></table>'
    )
    return _collapsible(
        "email-std",
        f"Email Standards ({_tip('MTA-STS')} / {_tip('TLSRPT')} / {_tip('BIMI')})",
        table,
    )


def _build_detail_dns_security(domains, dns_sec_results) -> str:
    if not dns_sec_results:
        return _collapsible("dns-sec", "DNS Security",
                            '<p style="color:#94a3b8;padding:16px">No DNS security data available.</p>')

    body_parts = []
    for domain in domains:
        result = dns_sec_results.get(domain)
        if not result:
            continue

        dnssec = result.get("dnssec", {})
        caa = result.get("caa", {})
        dangling = result.get("dangling", {})
        dang_list = dangling.get("dangling", [])

        rows = (
            f'<tr><td>{_tip("DNSSEC")}</td><td>{_badge(dnssec.get("grade", "INFO"))}</td>'
            f'<td>{_esc(dnssec.get("reason", ""))}</td></tr>'
            f'<tr><td>{_tip("CAA")}</td><td>{_badge(caa.get("grade", "INFO"))}</td>'
            f'<td>{_esc(caa.get("reason", ""))}</td></tr>'
            f'<tr><td>{_tip("Dangling CNAMEs")}</td><td>{_badge(dangling.get("grade", "INFO"))}</td>'
            f'<td>{len(dang_list)} dangling</td></tr>'
        )

        caa_records = caa.get("records", [])
        caa_html = ""
        if caa_records:
            caa_rows = "".join(
                f'<tr><td>{_esc(r.get("flags", ""))}</td>'
                f'<td><code>{_esc(r.get("tag", ""))}</code></td>'
                f'<td><code>{_esc(r.get("value", ""))}</code></td></tr>'
                for r in caa_records
            )
            caa_html = (
                f'<div style="margin-top:10px"><strong>CAA Records</strong></div>'
                f'<table><thead><tr><th>Flags</th><th>Tag</th><th>Value</th></tr></thead>'
                f'<tbody>{caa_rows}</tbody></table>'
            )

        dangling_html = ""
        if dang_list:
            dang_rows = "".join(
                f'<tr><td><code>{_esc(d["name"])}</code></td>'
                f'<td><code>{_esc(d["target"])}</code></td></tr>'
                for d in dang_list
            )
            dangling_html = (
                f'<div style="margin-top:10px"><strong>{_tip("Dangling CNAMEs")}</strong></div>'
                f'<table><thead><tr><th>Record</th><th>Target</th></tr></thead>'
                f'<tbody>{dang_rows}</tbody></table>'
            )

        body_parts.append(
            f'<h4 style="color:#60a5fa;margin:20px 0 8px"><code>{_esc(domain)}</code></h4>'
            f'<table><thead><tr><th>Check</th><th>Grade</th><th>Details</th></tr></thead>'
            f'<tbody>{rows}</tbody></table>'
            f'{caa_html}{dangling_html}'
        )

    return _collapsible("dns-sec", "DNS Security", "\n".join(body_parts))


def _build_detail_infrastructure(
    domains, registrar_results, blacklist_results, rdns_results,
) -> str:
    rows = ""
    for domain in domains:
        reg = registrar_results.get(domain, {})
        bl = blacklist_results.get(domain, {})
        rdns = rdns_results.get(domain, {})

        registrar_name = _esc(reg.get("registrar", _DASH))
        exp = reg.get("expiry", {})
        lock = reg.get("lock", {})

        rows += (
            f'<tr data-domain="{_esc(domain)}">'
            f'<td><code>{_esc(domain)}</code></td>'
            f'<td>{registrar_name}</td>'
            f'<td>{_badge(exp.get("grade", "INFO"))} <small>{_esc(exp.get("reason", ""))}</small></td>'
            f'<td>{_badge(lock.get("grade", "INFO"))} '
            f'<small>{"Locked" if lock.get("locked") else "Unlocked"}</small></td>'
            f'<td>{_badge(bl.get("grade", "INFO"))} <small>{_esc(bl.get("reason", ""))}</small></td>'
            f'<td>{_badge(rdns.get("grade", "INFO"))} <small>{_esc(rdns.get("reason", ""))}</small></td>'
            f'</tr>\n'
        )

    table = (
        '<table><thead><tr><th>Domain</th><th>Registrar</th>'
        f'<th>{_tip("Domain expiry")}</th><th>{_tip("Transfer lock")}</th>'
        f'<th>{_tip("Blacklist (DNSBL)")}</th><th>{_tip("Reverse DNS")}</th>'
        '</tr></thead>'
        f'<tbody>{rows}</tbody></table>'
    )
    return _collapsible("infra", "Infrastructure (Registrar, Blacklist, Reverse DNS)", table)


def _build_detail_dns_inventory(domains, dns_results) -> str:
    if not dns_results:
        return _collapsible("dns-inv", "DNS Inventory",
                            '<p style="color:#94a3b8;padding:16px">No DNS record data available.</p>')

    body_parts = []
    for domain in domains:
        summary = dns_results.get(domain)
        if not summary:
            continue

        type_pills = " ".join(
            f'<span class="badge badge-info">{_esc(t)}: {c}</span>'
            for t, c in summary["by_type"].items()
        )

        rows = ""
        for r in sorted(summary["records"], key=lambda x: (x["type"], x["name"])):
            proxied = '<span class="badge badge-warning">proxied</span>' if r["proxied"] else ""
            rows += (
                f"<tr>"
                f"<td><code>{_esc(r['type'])}</code></td>"
                f"<td><code>{_esc(r['name'])}</code></td>"
                f"<td><code>{_esc(_truncate(r['content'], 70))}</code></td>"
                f"<td>{r['ttl']}</td>"
                f"<td>{proxied}</td>"
                f"</tr>\n"
            )

        body_parts.append(
            f'<h4 style="color:#60a5fa;margin:20px 0 8px">'
            f'<code>{_esc(domain)}</code>'
            f' <span style="color:#94a3b8;font-weight:400">'
            f'{_DASH} {summary["total"]} records</span></h4>'
            f'<div style="margin-bottom:8px">{type_pills}</div>'
            f'<table><thead><tr><th>Type</th><th>Name</th><th>Content</th>'
            f'<th>TTL</th><th></th></tr></thead>'
            f'<tbody>{rows}</tbody></table>'
        )

    return _collapsible("dns-inv", "DNS Inventory", "\n".join(body_parts))
