"""
reporter.py — Report writer. Produces Markdown, HTML, and CSV output.

Markdown: human-readable, Git-friendly, good for the repo sample.
HTML:     visual dashboard, self-contained single file.
CSV:      machine-readable compliance summary, one row per domain.
"""

import csv
import html
from datetime import datetime, timezone
from typing import Dict, List

from cloudflare_reporting.lib.remediation import get_tooltip, collect_remediations


# ── Grade helpers ─────────────────────────────────────────────────────────────

_GRADE_ORDER = {"FAIL": 0, "WARN": 1, "INFO": 2, "PASS": 3}

GRADE_SYMBOL = {
    "PASS": "✅ PASS",
    "WARN": "⚠️ WARN",
    "FAIL": "❌ FAIL",
    "INFO": "ℹ️ INFO",
}

# HTML badge classes
GRADE_CLASS = {
    "PASS": "badge-success",
    "WARN": "badge-warning",
    "FAIL": "badge-danger",
    "INFO": "badge-info",
}


# Em dash for use in f-string expressions (backslash escapes not allowed in Python 3.10 f-exprs)
_DASH = "\u2014"


def _worst(grades: List[str]) -> str:
    if not grades:
        return "INFO"
    return min(grades, key=lambda g: _GRADE_ORDER.get(g, 99))


def _sym(grade: str) -> str:
    return GRADE_SYMBOL.get(grade, grade)


def _truncate(s: str, n: int = 80) -> str:
    return s if len(s) <= n else s[:n - 3] + "..."


def _ts() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


# ══════════════════════════════════════════════════════════════════════════════
# MARKDOWN
# ══════════════════════════════════════════════════════════════════════════════

def write_markdown(
    domains: List[str],
    dns_results: Dict[str, dict],
    email_results: Dict[str, dict],
    security_results: Dict[str, dict],
    registrar_results: Dict[str, dict],
    dns_sec_results: Dict[str, dict],
    blacklist_results: Dict[str, dict],
    rdns_results: Dict[str, dict],
    email_std_results: Dict[str, dict] = None,
    output_path: str = "",
) -> None:
    sections = [
        _md_header(domains),
        _md_executive_summary(
            domains, email_results, security_results, dns_results,
            registrar_results, dns_sec_results, blacklist_results, rdns_results,
        ),
    ]

    for domain in domains:
        if domain in registrar_results:
            sections.append(_md_registrar(domain, registrar_results[domain]))
        if domain in dns_sec_results:
            sections.append(_md_dns_security(domain, dns_sec_results[domain]))
        if domain in dns_results:
            sections.append(_md_dns(domain, dns_results[domain]))
        if domain in email_results:
            sections.append(_md_email(domain, email_results[domain]))
        if domain in blacklist_results:
            sections.append(_md_blacklist(domain, blacklist_results[domain]))
        if domain in rdns_results:
            sections.append(_md_rdns(domain, rdns_results[domain]))
        if email_std_results and domain in email_std_results:
            sections.append(_md_email_standards(domain, email_std_results[domain]))
        if domain in security_results:
            sections.append(_md_security(domain, security_results[domain]))

    sections.append(
        "\n---\n\n"
        "*Generated by [cloudflare-reporting](https://github.com/wblv-dev/cloudflare-reporting). "
        "Read-only — no changes made to any zone.*\n"
    )

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(sections))

    print(f"  Markdown report → {output_path}")


def _md_header(domains: List[str]) -> str:
    domain_list = ", ".join(f"`{d}`" for d in domains)
    return (
        f"# Cloudflare DNS Audit Report\n\n"
        f"**Generated:** {_ts()}  \n"
        f"**Domains:** {domain_list}  \n"
        f"**Tool:** [cloudflare-reporting](https://github.com/wblv-dev/cloudflare-reporting)\n\n"
        f"> Live DNS validation and Cloudflare API audit. "
        f"Grades reflect published state at time of generation.\n\n---\n"
    )


def _md_executive_summary(
    domains, email_results, security_results, dns_results,
    registrar_results, dns_sec_results, blacklist_results, rdns_results,
) -> str:
    lines = [
        "## Executive summary\n",
        "| Domain | DNS | Email | Zone | Registrar | DNSSEC | CAA | Blacklist | rDNS |",
        "|--------|-----|-------|------|-----------|--------|-----|-----------|------|",
    ]

    for d in domains:
        dns_count = dns_results.get(d, {}).get("total", "?")

        email = email_results.get(d, {})
        email_grade = _worst([
            email.get("spf", {}).get("grade", "INFO"),
            email.get("dmarc", {}).get("grade", "INFO"),
        ])

        sec = security_results.get(d)
        if sec:
            passed, total = sec["score"]
            sec_cell = f"{_sym(_worst([r['grade'] for r in sec['results']]))} ({passed}/{total})"
        else:
            sec_cell = "—"

        reg = registrar_results.get(d, {})
        reg_grade = _worst([
            reg.get("expiry", {}).get("grade", "INFO"),
            reg.get("lock", {}).get("grade", "INFO"),
        ])

        ds = dns_sec_results.get(d, {})
        dnssec_g = ds.get("dnssec", {}).get("grade", "?")
        caa_g = ds.get("caa", {}).get("grade", "?")

        bl_g = blacklist_results.get(d, {}).get("grade", "?")
        rdns_g = rdns_results.get(d, {}).get("grade", "?")

        lines.append(
            f"| `{d}` | {dns_count} | {_sym(email_grade)} | {sec_cell} "
            f"| {_sym(reg_grade)} | {_sym(dnssec_g)} | {_sym(caa_g)} "
            f"| {_sym(bl_g)} | {_sym(rdns_g)} |"
        )

    return "\n".join(lines) + "\n\n---\n"


def _md_registrar(domain: str, result: dict) -> str:
    lines = [f"## Registrar — `{domain}`\n"]

    if result.get("registrar"):
        lines.append(f"**Registrar:** {result['registrar']}\n")

    if result.get("nameservers"):
        lines.append(f"**Nameservers:** {', '.join(f'`{ns}`' for ns in result['nameservers'])}\n")

    exp = result.get("expiry", {})
    lines.append(f"**Expiry:** {_sym(exp.get('grade', 'INFO'))} — {exp.get('reason', 'Unknown')}")
    if exp.get("expiry"):
        lines.append(f"  \n**Expiry date:** `{exp['expiry']}`")

    lock = result.get("lock", {})
    lines.append(f"\n**Transfer lock:** {_sym(lock.get('grade', 'INFO'))} — {lock.get('reason', 'Unknown')}")

    return "\n".join(lines) + "\n\n"


def _md_dns_security(domain: str, result: dict) -> str:
    lines = [f"## DNS security — `{domain}`\n"]

    dnssec = result.get("dnssec", {})
    lines.append(f"**DNSSEC:** {_sym(dnssec.get('grade', 'INFO'))} — {dnssec.get('reason', '')}")

    caa = result.get("caa", {})
    lines.append(f"\n**CAA:** {_sym(caa.get('grade', 'INFO'))} — {caa.get('reason', '')}")

    if caa.get("records"):
        lines += ["\n| Flags | Tag | Value |", "|-------|-----|-------|"]
        for r in caa["records"]:
            lines.append(f"| {r.get('flags', '')} | `{r.get('tag', '')}` | `{r.get('value', '')}` |")

    dangling = result.get("dangling", {})
    lines.append(f"\n**Dangling CNAMEs:** {_sym(dangling.get('grade', 'INFO'))} — {dangling.get('reason', '')}")

    if dangling.get("dangling"):
        lines += ["\n| Record | Target |", "|--------|--------|"]
        for d in dangling["dangling"]:
            lines.append(f"| `{d['name']}` | `{d['target']}` |")

    return "\n".join(lines) + "\n\n"


def _md_blacklist(domain: str, result: dict) -> str:
    lines = [
        f"## Blacklist — `{domain}`\n",
        f"**Status:** {_sym(result.get('grade', 'INFO'))} — {result.get('reason', '')}",
    ]

    listings = result.get("listings", [])
    if listings:
        lines += ["\n| IP | Blacklist | Reason |", "|-----|-----------|--------|"]
        for l in listings:
            lines.append(f"| `{l.get('ip', '')}` | {l.get('blacklist', '')} | {l.get('reason', '')} |")

    return "\n".join(lines) + "\n\n"


def _md_rdns(domain: str, result: dict) -> str:
    lines = [
        f"## Reverse DNS — `{domain}`\n",
        f"**Status:** {_sym(result.get('grade', 'INFO'))} — {result.get('reason', '')}",
    ]

    ptr_results = result.get("results", [])
    if ptr_results:
        lines += ["\n| MX Host | IP | PTR | FCrDNS |", "|---------|-----|-----|--------|"]
        for r in ptr_results:
            fcrdns = "✅" if r.get("fcrdns") else "❌"
            ptr = r.get("ptr") or "—"
            lines.append(
                f"| `{r.get('mx_host', '')}` | `{r.get('ip', '')}` | `{ptr}` | {fcrdns} |"
            )

    return "\n".join(lines) + "\n\n"


def _md_email_standards(domain: str, result: dict) -> str:
    lines = [f"## Email standards — `{domain}`\n"]

    mta = result.get("mta_sts", {})
    lines.append(f"**MTA-STS:** {_sym(mta.get('grade', 'INFO'))} — {mta.get('reason', '')}")
    if mta.get("mode"):
        lines.append(f"  \n**Mode:** `{mta['mode']}`")

    tls = result.get("tlsrpt", {})
    lines.append(f"\n**TLSRPT:** {_sym(tls.get('grade', 'INFO'))} — {tls.get('reason', '')}")
    if tls.get("rua"):
        lines.append(f"  \n**Reporting:** `{tls['rua']}`")

    bimi = result.get("bimi", {})
    lines.append(f"\n**BIMI:** {_sym(bimi.get('grade', 'INFO'))} — {bimi.get('reason', '')}")

    return "\n".join(lines) + "\n\n"


def _md_dns(domain: str, summary: dict) -> str:
    lines = [f"## DNS inventory — `{domain}`\n",
             f"**Total:** {summary['total']} records  "
             f"(**{summary['proxied']}** proxied through Cloudflare)\n",
             "**By type:**\n",
             "| Type | Count |", "|------|-------|"]
    for rtype, count in summary["by_type"].items():
        lines.append(f"| `{rtype}` | {count} |")

    lines += ["\n**All records:**\n",
              "| Type | Name | Content | TTL | Proxied |",
              "|------|------|---------|-----|---------|"]
    for r in sorted(summary["records"], key=lambda x: (x["type"], x["name"])):
        proxied = "🟠 Yes" if r["proxied"] else "No"
        lines.append(
            f"| `{r['type']}` | `{r['name']}` "
            f"| `{_truncate(r['content'], 60)}` | {r['ttl']} | {proxied} |"
        )
    return "\n".join(lines) + "\n\n"


def _md_email(domain: str, result: dict) -> str:
    lines = [f"## Email security — `{domain}`\n"]

    if not result["has_mail"]:
        lines.append("**MX:** " + (
            "None — domain does not handle email.\n"
            if not result["mx"]
            else "Null MX (RFC 7505) — domain explicitly declares no mail.\n"
        ))
    else:
        lines += ["**MX records:**\n", "| Priority | Host |", "|----------|------|"]
        for mx in result["mx"]:
            lines.append(f"| {mx['priority']} | `{mx['host']}` |")
        lines.append("")

    spf   = result["spf"]
    dmarc = result["dmarc"]

    lines.append(f"**SPF:** {_sym(spf['grade'])} — {spf['reason']}")
    if spf.get("record"):
        lines.append(f"\n```\n{spf['record']}\n```\n")

    lines.append(f"**DMARC:** {_sym(dmarc['grade'])} — {dmarc['reason']}")
    if dmarc.get("rua"):
        lines.append(f"  \n**Reporting (rua):** `{dmarc['rua']}`")
    if dmarc.get("record"):
        lines.append(f"\n```\n{dmarc['record']}\n```\n")

    if result["dkim"]:
        lines += ["**DKIM selectors found:**\n",
                  "| Selector | Record (truncated) |",
                  "|----------|--------------------|"]
        for dk in result["dkim"]:
            lines.append(f"| `{dk['selector']}` | `{_truncate(dk['record'], 60)}` |")
    else:
        lines.append(
            "**DKIM:** No common selectors found. "
            "Add your provider's selector to `DKIM_SELECTORS` in `cloudflare_reporting/checks/email_security.py`.\n"
        )

    return "\n".join(lines) + "\n"


def _md_security(domain: str, result: dict) -> str:
    passed, total = result["score"]
    lines = [f"## Zone security — `{domain}`\n",
             f"**Score:** {passed}/{total} checks passed\n",
             "| Check | Recommended | Actual | Grade | Notes |",
             "|-------|-------------|--------|-------|-------|"]
    for r in result["results"]:
        lines.append(
            f"| {r['label']} | `{r.get('recommended','—')}` "
            f"| `{r.get('actual','—')}` | {_sym(r['grade'])} | {r.get('note','')} |"
        )

    failures = [r for r in result["results"] if r["grade"] in ("FAIL", "WARN")]
    if failures:
        lines.append("\n**Findings:**\n")
        for r in failures:
            if r.get("explanation"):
                lines.append(f"- **{r['label']}** ({_sym(r['grade'])}): {r['explanation']}")

    return "\n".join(lines) + "\n\n"


# ══════════════════════════════════════════════════════════════════════════════
# CSV
# ══════════════════════════════════════════════════════════════════════════════

def write_csv(
    domains: List[str],
    dns_results: Dict[str, dict],
    email_results: Dict[str, dict],
    security_results: Dict[str, dict],
    registrar_results: Dict[str, dict],
    dns_sec_results: Dict[str, dict],
    blacklist_results: Dict[str, dict],
    rdns_results: Dict[str, dict],
    email_std_results: Dict[str, dict] = None,
    output_path: str = "",
) -> None:
    """Write a CSV compliance summary — one row per domain."""
    fieldnames = [
        "Domain", "DNS Records",
        "SPF", "DMARC", "DKIM Selectors",
        "Zone Security", "Zone Pass", "Zone Total",
        "Registrar", "Expiry", "Expiry Days", "Transfer Lock",
        "DNSSEC", "CAA", "Dangling CNAMEs",
        "Blacklist", "Reverse DNS",
        "MTA-STS", "TLSRPT", "BIMI",
    ]

    _estd = email_std_results or {}
    rows = []
    for d in domains:
        dns = dns_results.get(d, {})
        email = email_results.get(d, {})
        sec = security_results.get(d, {})
        reg = registrar_results.get(d, {})
        ds = dns_sec_results.get(d, {})
        bl = blacklist_results.get(d, {})
        rdns = rdns_results.get(d, {})
        es = _estd.get(d, {})

        passed, total = sec.get("score", (0, 0))

        rows.append({
            "Domain":          d,
            "DNS Records":     dns.get("total", 0),
            "SPF":             email.get("spf", {}).get("grade", ""),
            "DMARC":           email.get("dmarc", {}).get("grade", ""),
            "DKIM Selectors":  len(email.get("dkim", [])),
            "Zone Security":   _worst([r["grade"] for r in sec.get("results", [])]) if sec.get("results") else "",
            "Zone Pass":       passed,
            "Zone Total":      total,
            "Registrar":       reg.get("registrar", ""),
            "Expiry":          reg.get("expiry", {}).get("grade", ""),
            "Expiry Days":     reg.get("expiry", {}).get("days_remaining", ""),
            "Transfer Lock":   reg.get("lock", {}).get("grade", ""),
            "DNSSEC":          ds.get("dnssec", {}).get("grade", ""),
            "CAA":             ds.get("caa", {}).get("grade", ""),
            "Dangling CNAMEs": len(ds.get("dangling", {}).get("dangling", [])),
            "Blacklist":       bl.get("grade", ""),
            "Reverse DNS":     rdns.get("grade", ""),
            "MTA-STS":         es.get("mta_sts", {}).get("grade", ""),
            "TLSRPT":          es.get("tlsrpt", {}).get("grade", ""),
            "BIMI":            es.get("bimi", {}).get("grade", ""),
        })

    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"  CSV report      → {output_path}")



# ══════════════════════════════════════════════════════════════════════════════
# HTML
# ══════════════════════════════════════════════════════════════════════════════

import json as _json
import os as _os


def _read_chartjs() -> str:
    """Read the Chart.js UMD bundle from /tmp/chartjs.min.js."""
    chartjs_path = _os.path.join("/tmp", "chartjs.min.js")
    try:
        with open(chartjs_path, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        return "/* Chart.js not found at /tmp/chartjs.min.js */"


def write_html(
    domains: List[str],
    dns_results: Dict[str, dict],
    email_results: Dict[str, dict],
    security_results: Dict[str, dict],
    registrar_results: Dict[str, dict],
    dns_sec_results: Dict[str, dict],
    blacklist_results: Dict[str, dict],
    rdns_results: Dict[str, dict],
    email_std_results: Dict[str, dict] = None,
    output_path: str = "",
) -> None:
    _estd = email_std_results or {}

    # Collect remediations
    remediations = collect_remediations(
        domains, security_results, email_results,
        dns_sec_results, registrar_results, blacklist_results, rdns_results,
    )

    # Aggregate grades across all domains
    all_grades = _collect_all_grades(
        domains, security_results, email_results,
        dns_sec_results, registrar_results, blacklist_results, rdns_results,
    )
    total_pass = all_grades["PASS"]
    total_warn = all_grades["WARN"]
    total_fail = all_grades["FAIL"]
    total_info = all_grades["INFO"]
    total_checks = total_pass + total_warn + total_fail + total_info
    compliance_pct = round(total_pass / total_checks * 100) if total_checks else 0

    # Category breakdown for stacked bar chart
    cat_data = _category_breakdown(
        domains, security_results, email_results,
        dns_sec_results, registrar_results, blacklist_results, rdns_results,
    )

    # Per-domain grade data for mini donuts
    domain_grades = {}
    for d in domains:
        dg = _collect_domain_grades(
            d, security_results, email_results,
            dns_sec_results, registrar_results, blacklist_results, rdns_results,
        )
        domain_grades[d] = dg

    out = "\n".join([
        _html_head(),
        _html_header_banner(domains, compliance_pct),
        '<div class="container">',
        # Section 2: Executive Summary
        _html_executive_summary(
            domains, total_pass, total_warn, total_fail, total_info,
            compliance_pct,
        ),
        # Section 3: Risk Overview
        _html_risk_overview(cat_data),
        # Section 4: Per-Domain Results
        _html_per_domain_results(
            domains, domain_grades, email_results, security_results,
            dns_results, registrar_results, dns_sec_results,
            blacklist_results, rdns_results,
        ),
        # Section 5: Findings & Remediations
        _html_findings_section(remediations),
        # Section 6: Detailed Check Results
        _html_detailed_checks(
            domains, security_results, email_results, _estd,
            dns_sec_results, registrar_results, blacklist_results,
            rdns_results, dns_results,
        ),
        '</div>',  # close .container
        _html_footer(),
        _html_charts_script(
            total_pass, total_warn, total_fail, total_info,
            cat_data, domains, domain_grades,
        ),
        '</body></html>',
    ])

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(out)

    print(f"  HTML report     \u2192 {output_path}")


# ── Helpers (must remain exactly as-is) ──────────────────────────────────────

def _esc(s) -> str:
    """HTML-escape untrusted content to prevent XSS."""
    if s is None:
        return ""
    return html.escape(str(s))


def _badge(grade: str, text: str = None) -> str:
    cls  = GRADE_CLASS.get(grade, "badge-info")
    label = text or grade
    return f'<span class="badge {cls}">{_esc(label)}</span>'


def _tip(label: str) -> str:
    """Wrap a label in a tooltip span if a tooltip exists for it."""
    tooltip_text = get_tooltip(label)
    if tooltip_text:
        return (
            f'<span class="has-tooltip" data-tooltip="{_esc(tooltip_text)}">'
            f'{_esc(label)}</span>'
        )
    return _esc(label)


# ── Grade aggregation helpers ────────────────────────────────────────────────

def _collect_all_grades(
    domains, security_results, email_results,
    dns_sec_results, registrar_results, blacklist_results, rdns_results,
) -> dict:
    """Count PASS/WARN/FAIL/INFO across every check on every domain."""
    counts = {"PASS": 0, "WARN": 0, "FAIL": 0, "INFO": 0}
    for d in domains:
        dg = _collect_domain_grades(
            d, security_results, email_results,
            dns_sec_results, registrar_results, blacklist_results, rdns_results,
        )
        for k in counts:
            counts[k] += dg.get(k, 0)
    return counts


def _collect_domain_grades(
    domain, security_results, email_results,
    dns_sec_results, registrar_results, blacklist_results, rdns_results,
) -> dict:
    """Count PASS/WARN/FAIL/INFO for a single domain."""
    counts = {"PASS": 0, "WARN": 0, "FAIL": 0, "INFO": 0}

    def _inc(grade: str) -> None:
        counts[grade] = counts.get(grade, 0) + 1

    sec = security_results.get(domain)
    if sec:
        for r in sec.get("results", []):
            _inc(r.get("grade", "INFO"))

    email = email_results.get(domain, {})
    for key in ("spf", "dmarc"):
        _inc(email.get(key, {}).get("grade", "INFO"))

    ds = dns_sec_results.get(domain, {})
    for key in ("dnssec", "caa", "dangling"):
        _inc(ds.get(key, {}).get("grade", "INFO"))

    reg = registrar_results.get(domain, {})
    for key in ("expiry", "lock"):
        _inc(reg.get(key, {}).get("grade", "INFO"))

    _inc(blacklist_results.get(domain, {}).get("grade", "INFO"))
    _inc(rdns_results.get(domain, {}).get("grade", "INFO"))

    return counts


def _category_breakdown(
    domains, security_results, email_results,
    dns_sec_results, registrar_results, blacklist_results, rdns_results,
) -> dict:
    """Return {category: {PASS, WARN, FAIL}} for the stacked bar chart."""
    cats = {
        "Zone Security": {"PASS": 0, "WARN": 0, "FAIL": 0},
        "Email": {"PASS": 0, "WARN": 0, "FAIL": 0},
        "DNS": {"PASS": 0, "WARN": 0, "FAIL": 0},
        "Infrastructure": {"PASS": 0, "WARN": 0, "FAIL": 0},
    }
    for d in domains:
        sec = security_results.get(d)
        if sec:
            for r in sec.get("results", []):
                g = r.get("grade", "INFO")
                if g in cats["Zone Security"]:
                    cats["Zone Security"][g] += 1

        email = email_results.get(d, {})
        for key in ("spf", "dmarc"):
            g = email.get(key, {}).get("grade", "INFO")
            if g in cats["Email"]:
                cats["Email"][g] += 1

        ds = dns_sec_results.get(d, {})
        for key in ("dnssec", "caa", "dangling"):
            g = ds.get(key, {}).get("grade", "INFO")
            if g in cats["DNS"]:
                cats["DNS"][g] += 1

        reg = registrar_results.get(d, {})
        for key in ("expiry", "lock"):
            g = reg.get(key, {}).get("grade", "INFO")
            if g in cats["Infrastructure"]:
                cats["Infrastructure"][g] += 1

        bl_g = blacklist_results.get(d, {}).get("grade", "INFO")
        if bl_g in cats["Infrastructure"]:
            cats["Infrastructure"][bl_g] += 1
        rdns_g = rdns_results.get(d, {}).get("grade", "INFO")
        if rdns_g in cats["Infrastructure"]:
            cats["Infrastructure"][rdns_g] += 1

    return cats


# ── Priority helpers ─────────────────────────────────────────────────────────

_PRIORITY_CLASS = {
    "Critical": "badge-danger",
    "High": "badge-warning",
    "Medium": "badge-info",
    "Low": "badge-info",
}

_PRIORITY_COLOR = {
    "Critical": "#dc2626",
    "High": "#d97706",
    "Medium": "#3b82f6",
    "Low": "#94a3b8",
}

_PRIORITY_BORDER = {
    "Critical": "#dc2626",
    "High": "#d97706",
    "Medium": "#eab308",
    "Low": "#3b82f6",
}


# ══════════════════════════════════════════════════════════════════════════════
# HTML sections
# ══════════════════════════════════════════════════════════════════════════════

def _html_head() -> str:
    chartjs_src = _read_chartjs()
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Security Audit Report</title>
<script>{chartjs_src}</script>
<style>
/* ── Reset & Base ──────────────────────────────────────────── */
*,*::before,*::after{{margin:0;padding:0;box-sizing:border-box}}
:root{{
  --bg:#0f172a;--bg-card:#1e293b;--text:#e2e8f0;--text-muted:#94a3b8;
  --border:#334155;--th-bg:#1e3a5f;--th-text:#e2e8f0;--hover-row:#334155;
  --code-bg:#334155;--shadow:0 2px 8px rgba(0,0,0,.3);
  --accent:#60a5fa;--accent-light:#93c5fd;
  --pass:#059669;--pass-bg:#d1fae5;--pass-bg-dark:#064e3b;--pass-text-dark:#6ee7b7;
  --warn:#d97706;--warn-bg:#fef3c7;--warn-bg-dark:#78350f;--warn-text-dark:#fcd34d;
  --fail:#dc2626;--fail-bg:#fee2e2;--fail-bg-dark:#7f1d1d;--fail-text-dark:#fca5a5;
  --info:#3b82f6;--info-bg:#dbeafe;--info-bg-dark:#1e3a8a;--info-text-dark:#93c5fd;
}}
body{{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;
  line-height:1.6;color:var(--text);background:var(--bg)}}
a{{color:var(--accent)}}

/* ── Header Banner ─────────────────────────────────────────── */
.header-banner{{
  background:linear-gradient(135deg,#0f172a 0%,#1e293b 40%,#1e3a5f 100%);
  color:#e2e8f0;padding:48px 24px;border-bottom:3px solid #334155}}
.header-banner-inner{{max-width:1200px;margin:0 auto;display:flex;
  justify-content:space-between;align-items:center;flex-wrap:wrap;gap:24px}}
.header-banner h1{{font-size:2em;font-weight:700;letter-spacing:-0.5px}}
.header-banner .subtitle{{opacity:.7;font-size:.95em;margin-top:4px}}
.compliance-hero{{text-align:center}}
.compliance-hero .pct{{font-size:3.5em;font-weight:800;line-height:1;
  background:linear-gradient(135deg,#60a5fa,#34d399);-webkit-background-clip:text;
  -webkit-text-fill-color:transparent;background-clip:text}}
.compliance-hero .pct-label{{font-size:.85em;opacity:.7;margin-top:4px}}

/* ── Container ─────────────────────────────────────────────── */
.container{{max-width:1200px;margin:0 auto;padding:32px 24px}}

/* ── Section headers ───────────────────────────────────────── */
.section-title{{font-size:1.4em;font-weight:700;color:#e2e8f0;margin:48px 0 20px;
  padding-bottom:12px;border-bottom:2px solid #334155}}

/* ── KPI cards ─────────────────────────────────────────────── */
.kpi-row{{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:20px;margin:28px 0}}
.kpi-card{{background:var(--bg-card);border:1px solid var(--border);border-radius:14px;
  padding:28px;text-align:center;box-shadow:var(--shadow);transition:transform .2s}}
.kpi-card:hover{{transform:translateY(-3px)}}
.kpi-card .kpi-num{{font-size:2.8em;font-weight:800;line-height:1.1}}
.kpi-card .kpi-label{{font-size:.8em;text-transform:uppercase;letter-spacing:1px;
  color:var(--text-muted);margin-top:6px}}
.kpi-green .kpi-num{{color:#34d399}}
.kpi-amber .kpi-num{{color:#fbbf24}}
.kpi-red .kpi-num{{color:#f87171}}
.kpi-blue .kpi-num{{color:#60a5fa}}

/* ── Chart containers ──────────────────────────────────────── */
.chart-row{{display:grid;grid-template-columns:340px 1fr;gap:32px;align-items:start;margin:28px 0}}
.chart-box{{background:var(--bg-card);border:1px solid var(--border);border-radius:14px;
  padding:24px;box-shadow:var(--shadow)}}
.chart-box h3{{font-size:1em;font-weight:600;margin-bottom:16px;color:var(--text-muted)}}
.chart-box canvas{{max-width:100%;height:auto}}

/* ── Domain result cards ───────────────────────────────────── */
.domain-result{{background:var(--bg-card);border:1px solid var(--border);border-radius:14px;
  padding:24px;margin-bottom:20px;box-shadow:var(--shadow)}}
.domain-result-header{{display:flex;justify-content:space-between;align-items:center;
  flex-wrap:wrap;gap:16px;margin-bottom:16px}}
.domain-result-header h3{{font-size:1.15em;font-weight:700;color:#e2e8f0}}
.domain-result-badges{{display:flex;gap:8px;flex-wrap:wrap}}
.domain-result-chart{{display:flex;align-items:center;gap:24px;flex-wrap:wrap}}
.domain-mini-donut{{width:100px;height:100px;flex-shrink:0}}
.domain-detail-toggle{{background:none;border:1px solid var(--border);color:var(--accent);
  padding:8px 18px;border-radius:8px;cursor:pointer;font-size:.85em;margin-top:12px;
  transition:background .2s}}
.domain-detail-toggle:hover{{background:rgba(96,165,250,.1)}}
.domain-detail-body{{max-height:0;overflow:hidden;transition:max-height .5s ease}}
.domain-detail-body.open{{max-height:5000px}}

/* ── Finding cards ─────────────────────────────────────────── */
.finding-card{{background:var(--bg-card);border:1px solid var(--border);border-radius:12px;
  padding:20px 24px;margin-bottom:14px;box-shadow:var(--shadow);
  border-left:4px solid #94a3b8}}
.finding-card.prio-critical{{border-left-color:#dc2626}}
.finding-card.prio-high{{border-left-color:#d97706}}
.finding-card.prio-medium{{border-left-color:#eab308}}
.finding-card.prio-low{{border-left-color:#3b82f6}}
.finding-header{{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-bottom:10px}}
.finding-risk{{margin:10px 0;padding:14px;background:rgba(220,38,38,.08);
  border-radius:8px;font-size:.9em;line-height:1.6;color:#fca5a5}}
.finding-steps{{margin:12px 0 0 20px;line-height:1.9;font-size:.9em}}
.finding-steps li{{margin-bottom:4px;color:var(--text-muted)}}

/* ── Collapsible sections ──────────────────────────────────── */
.collapsible-section{{margin-bottom:16px}}
.collapsible-header{{background:var(--bg-card);border:1px solid var(--border);border-radius:12px;
  padding:16px 24px;cursor:pointer;display:flex;justify-content:space-between;
  align-items:center;user-select:none;transition:background .2s;box-shadow:var(--shadow)}}
.collapsible-header:hover{{background:#263548}}
.collapsible-header h3{{font-size:1em;font-weight:600;color:var(--text)}}
.collapsible-chevron{{transition:transform .3s;font-size:.8em;color:var(--text-muted)}}
.collapsible-section.open .collapsible-chevron{{transform:rotate(180deg)}}
.collapsible-body{{max-height:0;overflow:hidden;transition:max-height .5s ease}}
.collapsible-section.open .collapsible-body{{max-height:10000px}}
.collapsible-body-inner{{padding:16px 0}}

/* ── Tables ────────────────────────────────────────────────── */
table{{width:100%;border-collapse:collapse;margin:12px 0;border-radius:10px;
  overflow:hidden;box-shadow:var(--shadow);background:var(--bg-card)}}
th{{background:var(--th-bg);color:var(--th-text);padding:12px 16px;text-align:left;
  font-size:.78em;font-weight:600;text-transform:uppercase;letter-spacing:.5px;
  white-space:nowrap}}
td{{padding:12px 16px;border-bottom:1px solid var(--border);font-size:.88em;
  vertical-align:top;color:var(--text)}}
tr:last-child td{{border-bottom:none}}
tr:hover td{{background:var(--hover-row)}}

/* ── Badges ────────────────────────────────────────────────── */
.badge{{display:inline-block;padding:3px 10px;border-radius:12px;
  font-size:.8em;font-weight:600;white-space:nowrap}}
.badge-success{{background:var(--pass-bg-dark);color:var(--pass-text-dark)}}
.badge-warning{{background:var(--warn-bg-dark);color:var(--warn-text-dark)}}
.badge-danger{{background:var(--fail-bg-dark);color:var(--fail-text-dark)}}
.badge-info{{background:var(--info-bg-dark);color:var(--info-text-dark)}}

/* ── Tooltips ──────────────────────────────────────────────── */
.has-tooltip{{position:relative;border-bottom:1px dotted var(--text-muted);cursor:help}}
.has-tooltip::after{{content:attr(data-tooltip);position:absolute;top:100%;margin-top:8px;
  left:0;background:#334155;color:#f1f5f9;padding:8px 12px;
  border-radius:8px;font-size:.78em;font-weight:400;white-space:normal;width:max-content;
  max-width:300px;line-height:1.4;box-shadow:0 4px 12px rgba(0,0,0,.4);z-index:1000;
  opacity:0;pointer-events:none;transition:opacity .2s .3s,transform .2s .3s;
  transform:translateY(-4px)}}
.has-tooltip:hover::after{{opacity:1;transform:translateY(0)}}
.has-tooltip::before{{content:"";position:absolute;top:100%;margin-top:-4px;left:12px;
  border:6px solid transparent;border-bottom-color:#334155;
  z-index:1001;opacity:0;pointer-events:none;transition:opacity .2s .3s}}
.has-tooltip:hover::before{{opacity:1}}
td{{position:relative}}
th .has-tooltip{{color:inherit;border-bottom-color:rgba(255,255,255,.4)}}

/* ── Code ──────────────────────────────────────────────────── */
code{{font-family:'SF Mono',Monaco,Consolas,monospace;background:var(--code-bg);
  padding:2px 6px;border-radius:4px;font-size:.85em;color:#93c5fd}}

/* ── Misc ──────────────────────────────────────────────────── */
.empty-state{{text-align:center;padding:40px;color:var(--text-muted);font-size:.95em}}
.footer{{text-align:center;padding:40px 24px;color:var(--text-muted);font-size:.85em;
  border-top:1px solid var(--border);margin-top:48px}}
.footer a{{color:var(--accent);text-decoration:none}}
.footer a:hover{{text-decoration:underline}}
.priority-group-header{{display:flex;align-items:center;gap:10px;margin:28px 0 14px;
  font-size:1.05em;font-weight:600}}

/* ── Responsive ────────────────────────────────────────────── */
@media(max-width:900px){{
  .chart-row{{grid-template-columns:1fr}}
  .header-banner-inner{{flex-direction:column;text-align:center}}
  .compliance-hero{{margin-top:8px}}
}}
@media(max-width:600px){{
  .kpi-row{{grid-template-columns:1fr 1fr}}
  .container{{padding:20px 14px}}
  .header-banner{{padding:32px 16px}}
  .header-banner h1{{font-size:1.5em}}
  td,th{{padding:8px 10px;font-size:.8em}}
}}

/* ── Print styles ──────────────────────────────────────────── */
@media print{{
  body{{background:#fff!important;color:#1a1a2e!important;font-size:11pt}}
  .header-banner{{background:#1a1a2e!important;-webkit-print-color-adjust:exact;
    print-color-adjust:exact}}
  .container{{padding:0}}
  .bg-card,.domain-result,.finding-card,.chart-box,.kpi-card,.collapsible-header{{
    background:#fff!important;border-color:#e2e8f0!important;color:#1a1a2e!important;
    box-shadow:none!important}}
  .kpi-card .kpi-label,.finding-steps li,td,th,.collapsible-header h3{{
    color:#1a1a2e!important}}
  .badge-success{{background:#d1fae5!important;color:#065f46!important}}
  .badge-warning{{background:#fef3c7!important;color:#92400e!important}}
  .badge-danger{{background:#fee2e2!important;color:#991b1b!important}}
  .badge-info{{background:#dbeafe!important;color:#1e40af!important}}
  code{{background:#f1f5f9!important;color:#1e40af!important}}
  .collapsible-body{{max-height:none!important}}
  .domain-detail-body{{max-height:none!important}}
  .domain-detail-toggle{{display:none}}
  .section-title{{color:#1a1a2e!important;border-color:#e2e8f0!important;
    page-break-before:always}}
  .section-title:first-of-type{{page-break-before:avoid}}
  th{{background:#0f3460!important;color:#fff!important;
    -webkit-print-color-adjust:exact;print-color-adjust:exact}}
  td{{border-color:#e2e8f0!important}}
  tr:hover td{{background:transparent!important}}
  .finding-risk{{background:rgba(220,38,38,.05)!important;color:#991b1b!important}}
}}
</style>
</head>
<body>"""


# ── Section 1: Header Banner ─────────────────────────────────────────────────

def _html_header_banner(domains: List[str], compliance_pct: int) -> str:
    domain_list = ", ".join(f"<code>{_esc(d)}</code>" for d in domains)
    return f"""
<div class="header-banner">
  <div class="header-banner-inner">
    <div>
      <h1>Security Audit Report</h1>
      <div class="subtitle">Generated {_ts()} {_DASH} {len(domains)} domain{"s" if len(domains) != 1 else ""} audited</div>
      <div class="subtitle" style="margin-top:4px">{domain_list}</div>
    </div>
    <div class="compliance-hero">
      <div class="pct">{compliance_pct}%</div>
      <div class="pct-label">Compliant</div>
    </div>
  </div>
</div>"""


# ── Section 2: Executive Summary ─────────────────────────────────────────────

def _html_executive_summary(
    domains, total_pass, total_warn, total_fail, total_info, compliance_pct,
) -> str:
    total_checks = total_pass + total_warn + total_fail + total_info
    return f"""
<h2 class="section-title">Executive Summary</h2>
<div class="chart-row">
  <div class="chart-box">
    <h3>Overall Compliance</h3>
    <canvas id="execDonut" width="280" height="280"></canvas>
  </div>
  <div>
    <div class="kpi-row">
      <div class="kpi-card kpi-blue">
        <div class="kpi-num">{len(domains)}</div>
        <div class="kpi-label">Domains Audited</div>
      </div>
      <div class="kpi-card kpi-green">
        <div class="kpi-num">{total_pass}</div>
        <div class="kpi-label">Checks Passed</div>
      </div>
      <div class="kpi-card kpi-amber">
        <div class="kpi-num">{total_warn}</div>
        <div class="kpi-label">Warnings</div>
      </div>
      <div class="kpi-card kpi-red">
        <div class="kpi-num">{total_fail}</div>
        <div class="kpi-label">Critical Failures</div>
      </div>
    </div>
    <div style="margin-top:12px;color:var(--text-muted);font-size:.9em">
      {total_checks} total checks across {len(domains)} domain{"s" if len(domains) != 1 else ""}.
      {compliance_pct}% of all checks passed successfully.
    </div>
  </div>
</div>"""


# ── Section 3: Risk Overview ─────────────────────────────────────────────────

def _html_risk_overview(cat_data: dict) -> str:
    return """
<h2 class="section-title">Risk Overview</h2>
<div class="chart-box" style="max-width:900px">
  <h3>Checks by Category</h3>
  <canvas id="riskBar" height="200"></canvas>
</div>"""


# ── Section 4: Per-Domain Results ────────────────────────────────────────────

def _html_per_domain_results(
    domains, domain_grades, email_results, security_results,
    dns_results, registrar_results, dns_sec_results,
    blacklist_results, rdns_results,
) -> str:
    parts = ['<h2 class="section-title">Per-Domain Results</h2>']

    for idx, domain in enumerate(domains):
        dg = domain_grades.get(domain, {})

        # Build grade badges
        email = email_results.get(domain, {})
        spf_g = email.get("spf", {}).get("grade", "INFO")
        dmarc_g = email.get("dmarc", {}).get("grade", "INFO")

        ds = dns_sec_results.get(domain, {})
        dnssec_g = ds.get("dnssec", {}).get("grade", "INFO")
        caa_g = ds.get("caa", {}).get("grade", "INFO")

        sec = security_results.get(domain)
        if sec:
            passed, total = sec["score"]
            sec_grade = _worst([r["grade"] for r in sec["results"]])
            zone_badge = _badge(sec_grade, f"Zone {passed}/{total}")
        else:
            zone_badge = _badge("INFO", "Zone N/A")

        bl_g = blacklist_results.get(domain, {}).get("grade", "INFO")
        rdns_g = rdns_results.get(domain, {}).get("grade", "INFO")

        # Build detail table
        detail_rows = ""
        if sec:
            for r in sec["results"]:
                detail_rows += (
                    f'<tr><td>Zone Security</td><td>{_tip(r["label"])}</td>'
                    f'<td><code>{_esc(r.get("recommended", _DASH))}</code></td>'
                    f'<td><code>{_esc(r.get("actual", _DASH))}</code></td>'
                    f'<td>{_badge(r["grade"])}</td></tr>\n'
                )

        for check_key, check_label, cat in [
            ("spf", "SPF", "Email"),
            ("dmarc", "DMARC", "Email"),
        ]:
            ck = email.get(check_key, {})
            detail_rows += (
                f'<tr><td>{_esc(cat)}</td><td>{_tip(check_label)}</td>'
                f'<td>{_DASH}</td>'
                f'<td><small>{_esc(ck.get("reason", ""))}</small></td>'
                f'<td>{_badge(ck.get("grade", "INFO"))}</td></tr>\n'
            )

        for check_key, check_label in [("dnssec", "DNSSEC"), ("caa", "CAA"), ("dangling", "Dangling CNAMEs")]:
            ck = ds.get(check_key, {})
            detail_rows += (
                f'<tr><td>DNS</td><td>{_tip(check_label)}</td>'
                f'<td>{_DASH}</td>'
                f'<td><small>{_esc(ck.get("reason", ""))}</small></td>'
                f'<td>{_badge(ck.get("grade", "INFO"))}</td></tr>\n'
            )

        reg = registrar_results.get(domain, {})
        for check_key, check_label in [("expiry", "Domain expiry"), ("lock", "Transfer lock")]:
            ck = reg.get(check_key, {})
            detail_rows += (
                f'<tr><td>Infrastructure</td><td>{_tip(check_label)}</td>'
                f'<td>{_DASH}</td>'
                f'<td><small>{_esc(ck.get("reason", ""))}</small></td>'
                f'<td>{_badge(ck.get("grade", "INFO"))}</td></tr>\n'
            )

        bl = blacklist_results.get(domain, {})
        detail_rows += (
            f'<tr><td>Infrastructure</td><td>{_tip("Blacklist (DNSBL)")}</td>'
            f'<td>{_DASH}</td>'
            f'<td><small>{_esc(bl.get("reason", ""))}</small></td>'
            f'<td>{_badge(bl.get("grade", "INFO"))}</td></tr>\n'
        )

        rdns = rdns_results.get(domain, {})
        detail_rows += (
            f'<tr><td>Infrastructure</td><td>{_tip("Reverse DNS")}</td>'
            f'<td>{_DASH}</td>'
            f'<td><small>{_esc(rdns.get("reason", ""))}</small></td>'
            f'<td>{_badge(rdns.get("grade", "INFO"))}</td></tr>\n'
        )

        dns_count = dns_results.get(domain, {}).get("total", 0)

        parts.append(f"""
<div class="domain-result" data-domain="{_esc(domain)}">
  <div class="domain-result-header">
    <h3>{_esc(domain)} <span style="color:var(--text-muted);font-weight:400;font-size:.8em">
      {_DASH} {dns_count} DNS records</span></h3>
    <div class="domain-result-badges">
      {_badge(spf_g, "SPF")} {_badge(dmarc_g, "DMARC")} {_badge(dnssec_g, "DNSSEC")}
      {_badge(caa_g, "CAA")} {zone_badge} {_badge(bl_g, "Blacklist")} {_badge(rdns_g, "rDNS")}
    </div>
  </div>
  <div class="domain-result-chart">
    <div class="domain-mini-donut">
      <canvas id="domainDonut{idx}" width="100" height="100"></canvas>
    </div>
    <div style="font-size:.88em;color:var(--text-muted)">
      <span style="color:#34d399">&#9679;</span> {dg.get("PASS", 0)} passed &nbsp;
      <span style="color:#fbbf24">&#9679;</span> {dg.get("WARN", 0)} warnings &nbsp;
      <span style="color:#f87171">&#9679;</span> {dg.get("FAIL", 0)} failures
    </div>
  </div>
  <button class="domain-detail-toggle" onclick="toggleDomainDetail(this)">Show detailed results</button>
  <div class="domain-detail-body">
    <table>
      <thead><tr><th>Category</th><th>Check</th><th>Recommended</th><th>Actual</th><th>Grade</th></tr></thead>
      <tbody>{detail_rows}</tbody>
    </table>
  </div>
</div>""")

    return "\n".join(parts)


# ── Section 5: Findings & Remediations ───────────────────────────────────────

def _html_findings_section(remediations: List[Dict]) -> str:
    if not remediations:
        return (
            '<h2 class="section-title">Findings &amp; Remediations</h2>'
            '<div class="empty-state">No findings requiring attention {_DASH} all checks passed.</div>'
        )

    # Group by priority
    groups: Dict[str, list] = {}
    for r in remediations:
        prio = r.get("priority", "Low")
        groups.setdefault(prio, []).append(r)

    count_by_prio = " / ".join(
        f'{len(groups.get(p, []))} {p}'
        for p in ["Critical", "High", "Medium", "Low"]
        if groups.get(p)
    )

    sections = [
        f'<h2 class="section-title">Findings &amp; Remediations</h2>',
        f'<div style="margin-bottom:20px;color:var(--text-muted);font-size:.9em">'
        f'{len(remediations)} finding{"s" if len(remediations) != 1 else ""} requiring attention: {count_by_prio}</div>',
    ]

    for prio in ["Critical", "High", "Medium", "Low"]:
        items = groups.get(prio, [])
        if not items:
            continue

        prio_cls = _PRIORITY_CLASS.get(prio, "badge-info")
        prio_color = _PRIORITY_COLOR.get(prio, "#94a3b8")
        prio_css = prio.lower()

        sections.append(
            f'<div class="priority-group-header">'
            f'<span class="badge {prio_cls}">{_esc(prio)}</span>'
            f'<span style="color:{prio_color}">'
            f'{len(items)} finding{"s" if len(items) != 1 else ""}</span></div>'
        )

        for finding in items:
            grade_badge = _badge(finding["grade"])
            prio_badge = f'<span class="badge {prio_cls}">{_esc(prio)}</span>'

            steps = finding.get("steps", [])
            steps_html = ""
            if steps:
                step_items = "".join(f'<li>{_esc(s)}</li>' for s in steps)
                steps_html = (
                    f'<div style="margin-top:10px"><strong style="color:var(--text)">Steps to fix:</strong></div>'
                    f'<ol class="finding-steps">{step_items}</ol>'
                )

            sections.append(
                f'<div class="finding-card prio-{prio_css}" data-domain="{_esc(finding.get("domain", ""))}">'
                f'<div class="finding-header">'
                f'{prio_badge} {grade_badge} '
                f'<strong>{_tip(finding.get("check", ""))}</strong>'
                f'<span style="color:var(--text-muted);font-size:.85em">'
                f'on <code>{_esc(finding.get("domain", ""))}</code></span>'
                f'</div>'
                f'<div class="finding-risk"><strong>Risk:</strong> {_esc(finding.get("risk", ""))}</div>'
                f'{steps_html}'
                f'</div>'
            )

    return "\n".join(sections)


# ── Section 6: Detailed Check Results ────────────────────────────────────────

def _html_detailed_checks(
    domains, security_results, email_results, email_std_results,
    dns_sec_results, registrar_results, blacklist_results,
    rdns_results, dns_results,
) -> str:
    parts = ['<h2 class="section-title">Detailed Check Results</h2>']

    # 6a: Zone Security Settings
    parts.append(_html_detail_zone_security(domains, security_results))

    # 6b: Email Security
    parts.append(_html_detail_email(domains, email_results))

    # 6c: Email Standards
    parts.append(_html_detail_email_standards(domains, email_std_results))

    # 6d: DNS Security
    parts.append(_html_detail_dns_security(domains, dns_sec_results))

    # 6e: Infrastructure
    parts.append(_html_detail_infrastructure(
        domains, registrar_results, blacklist_results, rdns_results,
    ))

    # 6f: DNS Inventory
    parts.append(_html_detail_dns_inventory(domains, dns_results))

    return "\n".join(parts)


def _collapsible(section_id: str, title: str, body: str) -> str:
    return (
        f'<div class="collapsible-section" id="section-{_esc(section_id)}">'
        f'<div class="collapsible-header" onclick="toggleCollapsible(this)">'
        f'<h3>{title}</h3>'
        f'<span class="collapsible-chevron" aria-hidden="true">&#9660;</span>'
        f'</div>'
        f'<div class="collapsible-body"><div class="collapsible-body-inner">{body}</div></div>'
        f'</div>'
    )


def _html_detail_zone_security(domains, security_results) -> str:
    if not security_results:
        return _collapsible("zone", "Zone Security Settings",
                            '<div class="empty-state">No zone security data available.</div>')
    rows = ""
    for domain in domains:
        sec = security_results.get(domain)
        if not sec:
            continue
        for r in sec["results"]:
            rows += (
                f'<tr data-domain="{_esc(domain)}">'
                f'<td><code>{_esc(domain)}</code></td>'
                f'<td>{_tip(r["label"])}</td>'
                f'<td><code>{_esc(r.get("recommended", _DASH))}</code></td>'
                f'<td><code>{_esc(r.get("actual", _DASH))}</code></td>'
                f'<td>{_badge(r["grade"])}</td></tr>\n'
            )

    table = (
        '<table><thead><tr><th>Domain</th><th>Check</th>'
        '<th>Recommended</th><th>Actual</th><th>Grade</th></tr></thead>'
        f'<tbody>{rows}</tbody></table>'
    )
    return _collapsible("zone", "Zone Security Settings", table)


def _html_detail_email(domains, email_results) -> str:
    if not email_results:
        return _collapsible("email", "Email Security",
                            '<div class="empty-state">No email security data available.</div>')

    body_parts = []
    for domain in domains:
        result = email_results.get(domain)
        if not result:
            continue

        spf = result["spf"]
        dmarc = result["dmarc"]
        dkim_count = len(result["dkim"])

        rows = (
            f'<tr><td>{_tip("SPF")}</td><td>{_badge(spf["grade"])}</td>'
            f'<td>{_esc(spf["reason"])}</td></tr>'
            f'<tr><td>{_tip("DMARC")}</td><td>{_badge(dmarc["grade"])}</td>'
            f'<td>{_esc(dmarc["reason"])}</td></tr>'
            f'<tr><td>{_tip("DKIM")}</td><td>{_badge("PASS" if dkim_count else "INFO")}</td>'
            f'<td>{dkim_count} selector(s) found</td></tr>'
        )

        spf_record = ""
        if spf.get("record"):
            spf_record = f'<div style="margin:8px 0"><code style="word-break:break-all;display:block;padding:10px;border-radius:6px">{_esc(spf["record"])}</code></div>'

        dmarc_record = ""
        if dmarc.get("record"):
            dmarc_record = f'<div style="margin:8px 0"><code style="word-break:break-all;display:block;padding:10px;border-radius:6px">{_esc(dmarc["record"])}</code></div>'

        dkim_html = ""
        if result["dkim"]:
            dkim_rows = "".join(
                f'<tr><td><code>{_esc(dk["selector"])}</code></td>'
                f'<td><code>{_esc(_truncate(dk["record"], 60))}</code></td></tr>'
                for dk in result["dkim"]
            )
            dkim_html = (
                f'<div style="margin-top:12px"><strong>{_tip("DKIM")} Selectors</strong></div>'
                f'<table><thead><tr><th>Selector</th><th>Record</th></tr></thead>'
                f'<tbody>{dkim_rows}</tbody></table>'
            )

        mx_html = ""
        if result["has_mail"] and result["mx"]:
            mx_rows = "".join(
                f'<tr><td>{m["priority"]}</td><td><code>{_esc(m["host"])}</code></td></tr>'
                for m in result["mx"]
            )
            mx_html = (
                f'<div style="margin-top:12px"><strong>MX Records</strong></div>'
                f'<table><thead><tr><th>Priority</th><th>Host</th></tr></thead>'
                f'<tbody>{mx_rows}</tbody></table>'
            )

        body_parts.append(
            f'<h4 style="color:var(--accent);margin:20px 0 8px"><code>{_esc(domain)}</code></h4>'
            f'<table><thead><tr><th>Check</th><th>Grade</th><th>Details</th></tr></thead>'
            f'<tbody>{rows}</tbody></table>'
            f'{spf_record}{dmarc_record}{mx_html}{dkim_html}'
        )

    return _collapsible("email", "Email Security", "\n".join(body_parts))


def _html_detail_email_standards(domains, email_std_results) -> str:
    if not email_std_results:
        return _collapsible("email-std", f"Email Standards ({_tip('MTA-STS')} / {_tip('TLSRPT')} / {_tip('BIMI')})",
                            '<div class="empty-state">No email standards data available.</div>')

    rows = ""
    for domain in domains:
        result = email_std_results.get(domain)
        if not result:
            continue
        mta = result.get("mta_sts", {})
        tls = result.get("tlsrpt", {})
        bimi = result.get("bimi", {})
        rows += (
            f'<tr data-domain="{_esc(domain)}">'
            f'<td><code>{_esc(domain)}</code></td>'
            f'<td>{_badge(mta.get("grade", "INFO"))} '
            f'<small>{_esc(mta.get("reason", ""))}</small></td>'
            f'<td>{_badge(tls.get("grade", "INFO"))} '
            f'<small>{_esc(tls.get("reason", ""))}</small></td>'
            f'<td>{_badge(bimi.get("grade", "INFO"))} '
            f'<small>{_esc(bimi.get("reason", ""))}</small></td></tr>\n'
        )

    table = (
        f'<table><thead><tr><th>Domain</th>'
        f'<th>{_tip("MTA-STS")}</th><th>{_tip("TLSRPT")}</th><th>{_tip("BIMI")}</th>'
        f'</tr></thead><tbody>{rows}</tbody></table>'
    )
    return _collapsible(
        "email-std",
        f"Email Standards ({_tip('MTA-STS')} / {_tip('TLSRPT')} / {_tip('BIMI')})",
        table,
    )


def _html_detail_dns_security(domains, dns_sec_results) -> str:
    if not dns_sec_results:
        return _collapsible("dns-sec", "DNS Security",
                            '<div class="empty-state">No DNS security data available.</div>')

    body_parts = []
    for domain in domains:
        result = dns_sec_results.get(domain)
        if not result:
            continue

        dnssec = result.get("dnssec", {})
        caa = result.get("caa", {})
        dangling = result.get("dangling", {})
        dang_list = dangling.get("dangling", [])

        rows = (
            f'<tr><td>{_tip("DNSSEC")}</td><td>{_badge(dnssec.get("grade", "INFO"))}</td>'
            f'<td>{_esc(dnssec.get("reason", ""))}</td></tr>'
            f'<tr><td>{_tip("CAA")}</td><td>{_badge(caa.get("grade", "INFO"))}</td>'
            f'<td>{_esc(caa.get("reason", ""))}</td></tr>'
            f'<tr><td>{_tip("Dangling CNAMEs")}</td><td>{_badge(dangling.get("grade", "INFO"))}</td>'
            f'<td>{len(dang_list)} dangling</td></tr>'
        )

        caa_records = caa.get("records", [])
        caa_html = ""
        if caa_records:
            caa_rows = "".join(
                f'<tr><td>{_esc(r.get("flags", ""))}</td>'
                f'<td><code>{_esc(r.get("tag", ""))}</code></td>'
                f'<td><code>{_esc(r.get("value", ""))}</code></td></tr>'
                for r in caa_records
            )
            caa_html = (
                f'<div style="margin-top:10px"><strong>CAA Records</strong></div>'
                f'<table><thead><tr><th>Flags</th><th>Tag</th><th>Value</th></tr></thead>'
                f'<tbody>{caa_rows}</tbody></table>'
            )

        dangling_html = ""
        if dang_list:
            dang_rows = "".join(
                f'<tr><td><code>{_esc(d["name"])}</code></td>'
                f'<td><code>{_esc(d["target"])}</code></td></tr>'
                for d in dang_list
            )
            dangling_html = (
                f'<div style="margin-top:10px"><strong>{_tip("Dangling CNAMEs")}</strong></div>'
                f'<table><thead><tr><th>Record</th><th>Target</th></tr></thead>'
                f'<tbody>{dang_rows}</tbody></table>'
            )

        body_parts.append(
            f'<h4 style="color:var(--accent);margin:20px 0 8px"><code>{_esc(domain)}</code></h4>'
            f'<table><thead><tr><th>Check</th><th>Grade</th><th>Details</th></tr></thead>'
            f'<tbody>{rows}</tbody></table>'
            f'{caa_html}{dangling_html}'
        )

    return _collapsible("dns-sec", "DNS Security", "\n".join(body_parts))


def _html_detail_infrastructure(
    domains, registrar_results, blacklist_results, rdns_results,
) -> str:
    rows = ""
    for domain in domains:
        reg = registrar_results.get(domain, {})
        bl = blacklist_results.get(domain, {})
        rdns = rdns_results.get(domain, {})

        registrar_name = _esc(reg.get("registrar", _DASH))
        exp = reg.get("expiry", {})
        lock = reg.get("lock", {})

        rows += (
            f'<tr data-domain="{_esc(domain)}">'
            f'<td><code>{_esc(domain)}</code></td>'
            f'<td>{registrar_name}</td>'
            f'<td>{_badge(exp.get("grade", "INFO"))} <small>{_esc(exp.get("reason", ""))}</small></td>'
            f'<td>{_badge(lock.get("grade", "INFO"))} '
            f'<small>{"Locked" if lock.get("locked") else "Unlocked"}</small></td>'
            f'<td>{_badge(bl.get("grade", "INFO"))} <small>{_esc(bl.get("reason", ""))}</small></td>'
            f'<td>{_badge(rdns.get("grade", "INFO"))} <small>{_esc(rdns.get("reason", ""))}</small></td>'
            f'</tr>\n'
        )

    table = (
        '<table><thead><tr><th>Domain</th><th>Registrar</th>'
        f'<th>{_tip("Domain expiry")}</th><th>{_tip("Transfer lock")}</th>'
        f'<th>{_tip("Blacklist (DNSBL)")}</th><th>{_tip("Reverse DNS")}</th>'
        '</tr></thead>'
        f'<tbody>{rows}</tbody></table>'
    )
    return _collapsible("infra", "Infrastructure (Registrar, Blacklist, Reverse DNS)", table)


def _html_detail_dns_inventory(domains, dns_results) -> str:
    if not dns_results:
        return _collapsible("dns-inv", "DNS Inventory",
                            '<div class="empty-state">No DNS record data available.</div>')

    body_parts = []
    for domain in domains:
        summary = dns_results.get(domain)
        if not summary:
            continue

        type_pills = " ".join(
            f'<span class="badge badge-info">{_esc(t)}: {c}</span>'
            for t, c in summary["by_type"].items()
        )

        rows = ""
        for r in sorted(summary["records"], key=lambda x: (x["type"], x["name"])):
            proxied = '<span class="badge badge-warning">proxied</span>' if r["proxied"] else ""
            rows += (
                f"<tr>"
                f"<td><code>{_esc(r['type'])}</code></td>"
                f"<td><code>{_esc(r['name'])}</code></td>"
                f"<td><code>{_esc(_truncate(r['content'], 70))}</code></td>"
                f"<td>{r['ttl']}</td>"
                f"<td>{proxied}</td>"
                f"</tr>\n"
            )

        body_parts.append(
            f'<h4 style="color:var(--accent);margin:20px 0 8px">'
            f'<code>{_esc(domain)}</code>'
            f' <span style="color:var(--text-muted);font-weight:400">'
            f'{_DASH} {summary["total"]} records</span></h4>'
            f'<div style="margin-bottom:8px">{type_pills}</div>'
            f'<table><thead><tr><th>Type</th><th>Name</th><th>Content</th>'
            f'<th>TTL</th><th></th></tr></thead>'
            f'<tbody>{rows}</tbody></table>'
        )

    return _collapsible("dns-inv", "DNS Inventory", "\n".join(body_parts))


# ── Section 7: Footer ────────────────────────────────────────────────────────

def _html_footer() -> str:
    return """
<div class="footer">
  Generated by <a href="https://github.com/wblv-dev/cloudflare-reporting">cloudflare-reporting</a>
  &middot; Read-only &mdash; no changes made to any zone.
</div>"""


# ── Chart.js initialization & interactive scripts ────────────────────────────

def _html_charts_script(
    total_pass, total_warn, total_fail, total_info,
    cat_data, domains, domain_grades,
) -> str:
    # Serialize data for JS
    cat_labels = _json.dumps(list(cat_data.keys()))
    cat_pass = _json.dumps([v["PASS"] for v in cat_data.values()])
    cat_warn = _json.dumps([v["WARN"] for v in cat_data.values()])
    cat_fail = _json.dumps([v["FAIL"] for v in cat_data.values()])

    domain_donut_js = ""
    for idx, domain in enumerate(domains):
        dg = domain_grades.get(domain, {})
        domain_donut_js += f"""
  (function(){{
    var ctx=document.getElementById('domainDonut{idx}');
    if(!ctx) return;
    new Chart(ctx,{{
      type:'doughnut',
      data:{{
        labels:['Passed','Warnings','Failures'],
        datasets:[{{
          data:[{dg.get("PASS",0)},{dg.get("WARN",0)},{dg.get("FAIL",0)}],
          backgroundColor:['#059669','#d97706','#dc2626'],
          borderWidth:0
        }}]
      }},
      options:{{
        responsive:false,
        plugins:{{legend:{{display:false}},tooltip:{{enabled:true}}}},
        cutout:'65%'
      }}
    }});
  }})();
"""

    return f"""
<script>
/* ── Executive donut ───────────────────────────────────────── */
(function(){{
  var ctx=document.getElementById('execDonut');
  if(!ctx) return;
  new Chart(ctx,{{
    type:'doughnut',
    data:{{
      labels:['Passed','Warnings','Failures','Informational'],
      datasets:[{{
        data:[{total_pass},{total_warn},{total_fail},{total_info}],
        backgroundColor:['#059669','#d97706','#dc2626','#3b82f6'],
        borderWidth:0,
        hoverBorderWidth:2,
        hoverBorderColor:'#e2e8f0'
      }}]
    }},
    options:{{
      responsive:true,
      maintainAspectRatio:true,
      cutout:'60%',
      plugins:{{
        legend:{{
          position:'bottom',
          labels:{{color:'#94a3b8',padding:16,font:{{size:12}},usePointStyle:true,pointStyle:'circle'}}
        }},
        tooltip:{{
          backgroundColor:'#1e293b',
          titleColor:'#e2e8f0',
          bodyColor:'#e2e8f0',
          borderColor:'#334155',
          borderWidth:1,
          cornerRadius:8
        }}
      }}
    }}
  }});
}})();

/* ── Risk stacked bar ──────────────────────────────────────── */
(function(){{
  var ctx=document.getElementById('riskBar');
  if(!ctx) return;
  new Chart(ctx,{{
    type:'bar',
    data:{{
      labels:{cat_labels},
      datasets:[
        {{label:'Passed',data:{cat_pass},backgroundColor:'#059669',borderRadius:4}},
        {{label:'Warnings',data:{cat_warn},backgroundColor:'#d97706',borderRadius:4}},
        {{label:'Failures',data:{cat_fail},backgroundColor:'#dc2626',borderRadius:4}}
      ]
    }},
    options:{{
      indexAxis:'y',
      responsive:true,
      maintainAspectRatio:true,
      scales:{{
        x:{{
          stacked:true,
          grid:{{color:'#334155'}},
          ticks:{{color:'#94a3b8',font:{{size:12}}}}
        }},
        y:{{
          stacked:true,
          grid:{{display:false}},
          ticks:{{color:'#e2e8f0',font:{{size:13,weight:'600'}}}}
        }}
      }},
      plugins:{{
        legend:{{
          position:'bottom',
          labels:{{color:'#94a3b8',padding:16,font:{{size:12}},usePointStyle:true,pointStyle:'circle'}}
        }},
        tooltip:{{
          backgroundColor:'#1e293b',
          titleColor:'#e2e8f0',
          bodyColor:'#e2e8f0',
          borderColor:'#334155',
          borderWidth:1,
          cornerRadius:8
        }}
      }}
    }}
  }});
}})();

/* ── Per-domain mini donuts ────────────────────────────────── */
{domain_donut_js}

/* ── Collapsible sections ──────────────────────────────────── */
function toggleCollapsible(header){{
  var section=header.parentElement;
  section.classList.toggle('open');
}}

/* ── Domain detail toggle ──────────────────────────────────── */
function toggleDomainDetail(btn){{
  var body=btn.nextElementSibling;
  if(body){{
    body.classList.toggle('open');
    btn.textContent=body.classList.contains('open')?'Hide detailed results':'Show detailed results';
  }}
}}
</script>"""
